/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "../rtl/movavg.v:1" *)
module movavg(clk, reset, din, dout);
  (* src = "../rtl/movavg.v:12" *)
  wire [5:0] _000_;
  (* src = "../rtl/movavg.v:12" *)
  wire [63:0] _001_;
  (* src = "../rtl/movavg.v:12" *)
  wire [63:0] _002_;
  (* src = "../rtl/movavg.v:12" *)
  wire [63:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  (* src = "../rtl/movavg.v:55" *)
  wire a1_s;
  (* src = "../rtl/movavg.v:55" *)
  wire a2_s;
  (* src = "../rtl/movavg.v:60" *)
  wire a3_s;
  (* src = "../rtl/movavg.v:1" *)
  input clk;
  (* src = "../rtl/movavg.v:31" *)
  wire ctl0;
  (* src = "../rtl/movavg.v:31" *)
  wire ctl1;
  (* src = "../rtl/movavg.v:31" *)
  wire ctl2;
  (* src = "../rtl/movavg.v:31" *)
  wire ctl3;
  (* src = "../rtl/movavg.v:10" *)
  wire [5:0] ctr;
  (* src = "../rtl/movavg.v:3" *)
  input [63:0] din;
  (* src = "../rtl/movavg.v:43" *)
  wire din_s;
  (* src = "../rtl/movavg.v:4" *)
  output [63:0] dout;
  (* src = "../rtl/movavg.v:2" *)
  input reset;
  (* src = "../rtl/movavg.v:6" *)
  wire [63:0] tap1;
  (* src = "../rtl/movavg.v:7" *)
  wire [63:0] tap2;
  (* src = "../rtl/movavg.v:8" *)
  wire [63:0] tap3;
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _015_ (
    .A(tap1[0]),
    .SLEEP(reset),
    .X(_002_[63])
  );
  sky130_fd_sc_hd__nor2_1 _016_ (
    .A(reset),
    .B(ctr[0]),
    .Y(_000_[0])
  );
  sky130_fd_sc_hd__xnor2_1 _017_ (
    .A(ctr[0]),
    .B(ctr[1]),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nor2_1 _018_ (
    .A(reset),
    .B(_004_),
    .Y(_000_[1])
  );
  sky130_fd_sc_hd__nand2_1 _019_ (
    .A(ctr[0]),
    .B(ctr[1]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__xor2_1 _020_ (
    .A(ctr[2]),
    .B(_005_),
    .X(_006_)
  );
  sky130_fd_sc_hd__nor2_1 _021_ (
    .A(reset),
    .B(_006_),
    .Y(_000_[2])
  );
  sky130_fd_sc_hd__nand3_1 _022_ (
    .A(ctr[0]),
    .B(ctr[2]),
    .C(ctr[1]),
    .Y(_007_)
  );
  sky130_fd_sc_hd__xor2_1 _023_ (
    .A(ctr[3]),
    .B(_007_),
    .X(_008_)
  );
  sky130_fd_sc_hd__nor2_1 _024_ (
    .A(reset),
    .B(_008_),
    .Y(_000_[3])
  );
  sky130_fd_sc_hd__inv_1 _025_ (
    .A(ctr[4]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nand4_1 _026_ (
    .A(ctr[0]),
    .B(ctr[2]),
    .C(ctr[3]),
    .D(ctr[1]),
    .Y(_010_)
  );
  sky130_fd_sc_hd__xnor2_1 _027_ (
    .A(_009_),
    .B(_010_),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nor2_1 _028_ (
    .A(reset),
    .B(_011_),
    .Y(_000_[4])
  );
  sky130_fd_sc_hd__o21ai_0 _029_ (
    .A1(_009_),
    .A2(_010_),
    .B1(ctr[5]),
    .Y(_012_)
  );
  sky130_fd_sc_hd__or3_1 _030_ (
    .A(_009_),
    .B(ctr[5]),
    .C(_010_),
    .X(_013_)
  );
  sky130_fd_sc_hd__a21oi_1 _031_ (
    .A1(_012_),
    .A2(_013_),
    .B1(reset),
    .Y(_000_[5])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _032_ (
    .A(tap1[1]),
    .SLEEP(reset),
    .X(_001_[0])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _033_ (
    .A(tap1[2]),
    .SLEEP(reset),
    .X(_001_[1])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _034_ (
    .A(tap1[3]),
    .SLEEP(reset),
    .X(_001_[2])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _035_ (
    .A(tap1[4]),
    .SLEEP(reset),
    .X(_001_[3])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _036_ (
    .A(tap1[5]),
    .SLEEP(reset),
    .X(_001_[4])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _037_ (
    .A(tap1[6]),
    .SLEEP(reset),
    .X(_001_[5])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _038_ (
    .A(tap1[7]),
    .SLEEP(reset),
    .X(_001_[6])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _039_ (
    .A(tap1[8]),
    .SLEEP(reset),
    .X(_001_[7])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _040_ (
    .A(tap1[9]),
    .SLEEP(reset),
    .X(_001_[8])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _041_ (
    .A(tap1[10]),
    .SLEEP(reset),
    .X(_001_[9])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _042_ (
    .A(tap1[11]),
    .SLEEP(reset),
    .X(_001_[10])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _043_ (
    .A(tap1[12]),
    .SLEEP(reset),
    .X(_001_[11])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _044_ (
    .A(tap1[13]),
    .SLEEP(reset),
    .X(_001_[12])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _045_ (
    .A(tap1[14]),
    .SLEEP(reset),
    .X(_001_[13])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _046_ (
    .A(tap1[15]),
    .SLEEP(reset),
    .X(_001_[14])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _047_ (
    .A(tap1[16]),
    .SLEEP(reset),
    .X(_001_[15])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _048_ (
    .A(tap1[17]),
    .SLEEP(reset),
    .X(_001_[16])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _049_ (
    .A(tap1[18]),
    .SLEEP(reset),
    .X(_001_[17])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _050_ (
    .A(tap1[19]),
    .SLEEP(reset),
    .X(_001_[18])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _051_ (
    .A(tap1[20]),
    .SLEEP(reset),
    .X(_001_[19])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _052_ (
    .A(tap1[21]),
    .SLEEP(reset),
    .X(_001_[20])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _053_ (
    .A(tap1[22]),
    .SLEEP(reset),
    .X(_001_[21])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _054_ (
    .A(tap1[23]),
    .SLEEP(reset),
    .X(_001_[22])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _055_ (
    .A(tap1[24]),
    .SLEEP(reset),
    .X(_001_[23])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _056_ (
    .A(tap1[25]),
    .SLEEP(reset),
    .X(_001_[24])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _057_ (
    .A(tap1[26]),
    .SLEEP(reset),
    .X(_001_[25])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _058_ (
    .A(tap1[27]),
    .SLEEP(reset),
    .X(_001_[26])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _059_ (
    .A(tap1[28]),
    .SLEEP(reset),
    .X(_001_[27])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _060_ (
    .A(tap1[29]),
    .SLEEP(reset),
    .X(_001_[28])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _061_ (
    .A(tap1[30]),
    .SLEEP(reset),
    .X(_001_[29])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _062_ (
    .A(tap1[31]),
    .SLEEP(reset),
    .X(_001_[30])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _063_ (
    .A(tap1[32]),
    .SLEEP(reset),
    .X(_001_[31])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _064_ (
    .A(tap1[33]),
    .SLEEP(reset),
    .X(_001_[32])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _065_ (
    .A(tap1[34]),
    .SLEEP(reset),
    .X(_001_[33])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _066_ (
    .A(tap1[35]),
    .SLEEP(reset),
    .X(_001_[34])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _067_ (
    .A(tap1[36]),
    .SLEEP(reset),
    .X(_001_[35])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _068_ (
    .A(tap1[37]),
    .SLEEP(reset),
    .X(_001_[36])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _069_ (
    .A(tap1[38]),
    .SLEEP(reset),
    .X(_001_[37])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _070_ (
    .A(tap1[39]),
    .SLEEP(reset),
    .X(_001_[38])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _071_ (
    .A(tap1[40]),
    .SLEEP(reset),
    .X(_001_[39])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _072_ (
    .A(tap1[41]),
    .SLEEP(reset),
    .X(_001_[40])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _073_ (
    .A(tap1[42]),
    .SLEEP(reset),
    .X(_001_[41])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _074_ (
    .A(tap1[43]),
    .SLEEP(reset),
    .X(_001_[42])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _075_ (
    .A(tap1[44]),
    .SLEEP(reset),
    .X(_001_[43])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _076_ (
    .A(tap1[45]),
    .SLEEP(reset),
    .X(_001_[44])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _077_ (
    .A(tap1[46]),
    .SLEEP(reset),
    .X(_001_[45])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _078_ (
    .A(tap1[47]),
    .SLEEP(reset),
    .X(_001_[46])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _079_ (
    .A(tap1[48]),
    .SLEEP(reset),
    .X(_001_[47])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _080_ (
    .A(tap1[49]),
    .SLEEP(reset),
    .X(_001_[48])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _081_ (
    .A(tap1[50]),
    .SLEEP(reset),
    .X(_001_[49])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _082_ (
    .A(tap1[51]),
    .SLEEP(reset),
    .X(_001_[50])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _083_ (
    .A(tap1[52]),
    .SLEEP(reset),
    .X(_001_[51])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _084_ (
    .A(tap1[53]),
    .SLEEP(reset),
    .X(_001_[52])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _085_ (
    .A(tap1[54]),
    .SLEEP(reset),
    .X(_001_[53])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _086_ (
    .A(tap1[55]),
    .SLEEP(reset),
    .X(_001_[54])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _087_ (
    .A(tap1[56]),
    .SLEEP(reset),
    .X(_001_[55])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _088_ (
    .A(tap1[57]),
    .SLEEP(reset),
    .X(_001_[56])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _089_ (
    .A(tap1[58]),
    .SLEEP(reset),
    .X(_001_[57])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _090_ (
    .A(tap1[59]),
    .SLEEP(reset),
    .X(_001_[58])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _091_ (
    .A(tap1[60]),
    .SLEEP(reset),
    .X(_001_[59])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _092_ (
    .A(tap1[61]),
    .SLEEP(reset),
    .X(_001_[60])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _093_ (
    .A(tap1[62]),
    .SLEEP(reset),
    .X(_001_[61])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _094_ (
    .A(tap1[63]),
    .SLEEP(reset),
    .X(_001_[62])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _095_ (
    .A(din_s),
    .SLEEP(reset),
    .X(_001_[63])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _096_ (
    .A(tap3[1]),
    .SLEEP(reset),
    .X(_003_[0])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _097_ (
    .A(tap3[2]),
    .SLEEP(reset),
    .X(_003_[1])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _098_ (
    .A(tap3[3]),
    .SLEEP(reset),
    .X(_003_[2])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _099_ (
    .A(tap3[4]),
    .SLEEP(reset),
    .X(_003_[3])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _100_ (
    .A(tap3[5]),
    .SLEEP(reset),
    .X(_003_[4])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _101_ (
    .A(tap3[6]),
    .SLEEP(reset),
    .X(_003_[5])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _102_ (
    .A(tap3[7]),
    .SLEEP(reset),
    .X(_003_[6])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _103_ (
    .A(tap3[8]),
    .SLEEP(reset),
    .X(_003_[7])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _104_ (
    .A(tap3[9]),
    .SLEEP(reset),
    .X(_003_[8])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _105_ (
    .A(tap3[10]),
    .SLEEP(reset),
    .X(_003_[9])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _106_ (
    .A(tap3[11]),
    .SLEEP(reset),
    .X(_003_[10])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _107_ (
    .A(tap3[12]),
    .SLEEP(reset),
    .X(_003_[11])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _108_ (
    .A(tap3[13]),
    .SLEEP(reset),
    .X(_003_[12])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _109_ (
    .A(tap3[14]),
    .SLEEP(reset),
    .X(_003_[13])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _110_ (
    .A(tap3[15]),
    .SLEEP(reset),
    .X(_003_[14])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _111_ (
    .A(tap3[16]),
    .SLEEP(reset),
    .X(_003_[15])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _112_ (
    .A(tap3[17]),
    .SLEEP(reset),
    .X(_003_[16])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _113_ (
    .A(tap3[18]),
    .SLEEP(reset),
    .X(_003_[17])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _114_ (
    .A(tap3[19]),
    .SLEEP(reset),
    .X(_003_[18])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _115_ (
    .A(tap3[20]),
    .SLEEP(reset),
    .X(_003_[19])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _116_ (
    .A(tap3[21]),
    .SLEEP(reset),
    .X(_003_[20])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _117_ (
    .A(tap3[22]),
    .SLEEP(reset),
    .X(_003_[21])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _118_ (
    .A(tap3[23]),
    .SLEEP(reset),
    .X(_003_[22])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _119_ (
    .A(tap3[24]),
    .SLEEP(reset),
    .X(_003_[23])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _120_ (
    .A(tap3[25]),
    .SLEEP(reset),
    .X(_003_[24])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _121_ (
    .A(tap3[26]),
    .SLEEP(reset),
    .X(_003_[25])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _122_ (
    .A(tap3[27]),
    .SLEEP(reset),
    .X(_003_[26])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _123_ (
    .A(tap3[28]),
    .SLEEP(reset),
    .X(_003_[27])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _124_ (
    .A(tap3[29]),
    .SLEEP(reset),
    .X(_003_[28])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _125_ (
    .A(tap3[30]),
    .SLEEP(reset),
    .X(_003_[29])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _126_ (
    .A(tap3[31]),
    .SLEEP(reset),
    .X(_003_[30])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _127_ (
    .A(tap3[32]),
    .SLEEP(reset),
    .X(_003_[31])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _128_ (
    .A(tap3[33]),
    .SLEEP(reset),
    .X(_003_[32])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _129_ (
    .A(tap3[34]),
    .SLEEP(reset),
    .X(_003_[33])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _130_ (
    .A(tap3[35]),
    .SLEEP(reset),
    .X(_003_[34])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _131_ (
    .A(tap3[36]),
    .SLEEP(reset),
    .X(_003_[35])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _132_ (
    .A(tap3[37]),
    .SLEEP(reset),
    .X(_003_[36])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _133_ (
    .A(tap3[38]),
    .SLEEP(reset),
    .X(_003_[37])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _134_ (
    .A(tap3[39]),
    .SLEEP(reset),
    .X(_003_[38])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _135_ (
    .A(tap3[40]),
    .SLEEP(reset),
    .X(_003_[39])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _136_ (
    .A(tap3[41]),
    .SLEEP(reset),
    .X(_003_[40])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _137_ (
    .A(tap3[42]),
    .SLEEP(reset),
    .X(_003_[41])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _138_ (
    .A(tap3[43]),
    .SLEEP(reset),
    .X(_003_[42])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _139_ (
    .A(tap3[44]),
    .SLEEP(reset),
    .X(_003_[43])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _140_ (
    .A(tap3[45]),
    .SLEEP(reset),
    .X(_003_[44])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _141_ (
    .A(tap3[46]),
    .SLEEP(reset),
    .X(_003_[45])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _142_ (
    .A(tap3[47]),
    .SLEEP(reset),
    .X(_003_[46])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _143_ (
    .A(tap3[48]),
    .SLEEP(reset),
    .X(_003_[47])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _144_ (
    .A(tap3[49]),
    .SLEEP(reset),
    .X(_003_[48])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _145_ (
    .A(tap3[50]),
    .SLEEP(reset),
    .X(_003_[49])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _146_ (
    .A(tap3[51]),
    .SLEEP(reset),
    .X(_003_[50])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _147_ (
    .A(tap3[52]),
    .SLEEP(reset),
    .X(_003_[51])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _148_ (
    .A(tap3[53]),
    .SLEEP(reset),
    .X(_003_[52])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _149_ (
    .A(tap3[54]),
    .SLEEP(reset),
    .X(_003_[53])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _150_ (
    .A(tap3[55]),
    .SLEEP(reset),
    .X(_003_[54])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _151_ (
    .A(tap3[56]),
    .SLEEP(reset),
    .X(_003_[55])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _152_ (
    .A(tap3[57]),
    .SLEEP(reset),
    .X(_003_[56])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _153_ (
    .A(tap3[58]),
    .SLEEP(reset),
    .X(_003_[57])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _154_ (
    .A(tap3[59]),
    .SLEEP(reset),
    .X(_003_[58])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _155_ (
    .A(tap3[60]),
    .SLEEP(reset),
    .X(_003_[59])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _156_ (
    .A(tap3[61]),
    .SLEEP(reset),
    .X(_003_[60])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _157_ (
    .A(tap3[62]),
    .SLEEP(reset),
    .X(_003_[61])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _158_ (
    .A(tap3[63]),
    .SLEEP(reset),
    .X(_003_[62])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _159_ (
    .A(tap2[0]),
    .SLEEP(reset),
    .X(_003_[63])
  );
  sky130_fd_sc_hd__or4_4 _160_ (
    .A(ctr[2]),
    .B(ctr[3]),
    .C(ctr[4]),
    .D(ctr[5]),
    .X(_014_)
  );
  sky130_fd_sc_hd__nor3_1 _161_ (
    .A(ctr[0]),
    .B(ctr[1]),
    .C(_014_),
    .Y(ctl0)
  );
  sky130_fd_sc_hd__nor3b_1 _162_ (
    .A(ctr[1]),
    .B(_014_),
    .C_N(ctr[0]),
    .Y(ctl1)
  );
  sky130_fd_sc_hd__nor3b_1 _163_ (
    .A(_014_),
    .B(ctr[0]),
    .C_N(ctr[1]),
    .Y(ctl2)
  );
  sky130_fd_sc_hd__nor2_1 _164_ (
    .A(_005_),
    .B(_014_),
    .Y(ctl3)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _165_ (
    .A(tap2[1]),
    .SLEEP(reset),
    .X(_002_[0])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _166_ (
    .A(tap2[2]),
    .SLEEP(reset),
    .X(_002_[1])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _167_ (
    .A(tap2[3]),
    .SLEEP(reset),
    .X(_002_[2])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _168_ (
    .A(tap2[4]),
    .SLEEP(reset),
    .X(_002_[3])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _169_ (
    .A(tap2[5]),
    .SLEEP(reset),
    .X(_002_[4])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _170_ (
    .A(tap2[6]),
    .SLEEP(reset),
    .X(_002_[5])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _171_ (
    .A(tap2[7]),
    .SLEEP(reset),
    .X(_002_[6])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _172_ (
    .A(tap2[8]),
    .SLEEP(reset),
    .X(_002_[7])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _173_ (
    .A(tap2[9]),
    .SLEEP(reset),
    .X(_002_[8])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _174_ (
    .A(tap2[10]),
    .SLEEP(reset),
    .X(_002_[9])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _175_ (
    .A(tap2[11]),
    .SLEEP(reset),
    .X(_002_[10])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _176_ (
    .A(tap2[12]),
    .SLEEP(reset),
    .X(_002_[11])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _177_ (
    .A(tap2[13]),
    .SLEEP(reset),
    .X(_002_[12])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _178_ (
    .A(tap2[14]),
    .SLEEP(reset),
    .X(_002_[13])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _179_ (
    .A(tap2[15]),
    .SLEEP(reset),
    .X(_002_[14])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _180_ (
    .A(tap2[16]),
    .SLEEP(reset),
    .X(_002_[15])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _181_ (
    .A(tap2[17]),
    .SLEEP(reset),
    .X(_002_[16])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _182_ (
    .A(tap2[18]),
    .SLEEP(reset),
    .X(_002_[17])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _183_ (
    .A(tap2[19]),
    .SLEEP(reset),
    .X(_002_[18])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _184_ (
    .A(tap2[20]),
    .SLEEP(reset),
    .X(_002_[19])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _185_ (
    .A(tap2[21]),
    .SLEEP(reset),
    .X(_002_[20])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _186_ (
    .A(tap2[22]),
    .SLEEP(reset),
    .X(_002_[21])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _187_ (
    .A(tap2[23]),
    .SLEEP(reset),
    .X(_002_[22])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _188_ (
    .A(tap2[24]),
    .SLEEP(reset),
    .X(_002_[23])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _189_ (
    .A(tap2[25]),
    .SLEEP(reset),
    .X(_002_[24])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _190_ (
    .A(tap2[26]),
    .SLEEP(reset),
    .X(_002_[25])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _191_ (
    .A(tap2[27]),
    .SLEEP(reset),
    .X(_002_[26])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _192_ (
    .A(tap2[28]),
    .SLEEP(reset),
    .X(_002_[27])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _193_ (
    .A(tap2[29]),
    .SLEEP(reset),
    .X(_002_[28])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _194_ (
    .A(tap2[30]),
    .SLEEP(reset),
    .X(_002_[29])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _195_ (
    .A(tap2[31]),
    .SLEEP(reset),
    .X(_002_[30])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _196_ (
    .A(tap2[32]),
    .SLEEP(reset),
    .X(_002_[31])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _197_ (
    .A(tap2[33]),
    .SLEEP(reset),
    .X(_002_[32])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _198_ (
    .A(tap2[34]),
    .SLEEP(reset),
    .X(_002_[33])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _199_ (
    .A(tap2[35]),
    .SLEEP(reset),
    .X(_002_[34])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _200_ (
    .A(tap2[36]),
    .SLEEP(reset),
    .X(_002_[35])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _201_ (
    .A(tap2[37]),
    .SLEEP(reset),
    .X(_002_[36])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _202_ (
    .A(tap2[38]),
    .SLEEP(reset),
    .X(_002_[37])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _203_ (
    .A(tap2[39]),
    .SLEEP(reset),
    .X(_002_[38])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _204_ (
    .A(tap2[40]),
    .SLEEP(reset),
    .X(_002_[39])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _205_ (
    .A(tap2[41]),
    .SLEEP(reset),
    .X(_002_[40])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _206_ (
    .A(tap2[42]),
    .SLEEP(reset),
    .X(_002_[41])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _207_ (
    .A(tap2[43]),
    .SLEEP(reset),
    .X(_002_[42])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _208_ (
    .A(tap2[44]),
    .SLEEP(reset),
    .X(_002_[43])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _209_ (
    .A(tap2[45]),
    .SLEEP(reset),
    .X(_002_[44])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _210_ (
    .A(tap2[46]),
    .SLEEP(reset),
    .X(_002_[45])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _211_ (
    .A(tap2[47]),
    .SLEEP(reset),
    .X(_002_[46])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _212_ (
    .A(tap2[48]),
    .SLEEP(reset),
    .X(_002_[47])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _213_ (
    .A(tap2[49]),
    .SLEEP(reset),
    .X(_002_[48])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _214_ (
    .A(tap2[50]),
    .SLEEP(reset),
    .X(_002_[49])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _215_ (
    .A(tap2[51]),
    .SLEEP(reset),
    .X(_002_[50])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _216_ (
    .A(tap2[52]),
    .SLEEP(reset),
    .X(_002_[51])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _217_ (
    .A(tap2[53]),
    .SLEEP(reset),
    .X(_002_[52])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _218_ (
    .A(tap2[54]),
    .SLEEP(reset),
    .X(_002_[53])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _219_ (
    .A(tap2[55]),
    .SLEEP(reset),
    .X(_002_[54])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _220_ (
    .A(tap2[56]),
    .SLEEP(reset),
    .X(_002_[55])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _221_ (
    .A(tap2[57]),
    .SLEEP(reset),
    .X(_002_[56])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _222_ (
    .A(tap2[58]),
    .SLEEP(reset),
    .X(_002_[57])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _223_ (
    .A(tap2[59]),
    .SLEEP(reset),
    .X(_002_[58])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _224_ (
    .A(tap2[60]),
    .SLEEP(reset),
    .X(_002_[59])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _225_ (
    .A(tap2[61]),
    .SLEEP(reset),
    .X(_002_[60])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _226_ (
    .A(tap2[62]),
    .SLEEP(reset),
    .X(_002_[61])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _227_ (
    .A(tap2[63]),
    .SLEEP(reset),
    .X(_002_[62])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _228_ (
    .CLK(clk),
    .D(_003_[0]),
    .Q(tap3[0])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _229_ (
    .CLK(clk),
    .D(_003_[1]),
    .Q(tap3[1])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _230_ (
    .CLK(clk),
    .D(_003_[2]),
    .Q(tap3[2])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _231_ (
    .CLK(clk),
    .D(_003_[3]),
    .Q(tap3[3])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _232_ (
    .CLK(clk),
    .D(_003_[4]),
    .Q(tap3[4])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _233_ (
    .CLK(clk),
    .D(_003_[5]),
    .Q(tap3[5])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _234_ (
    .CLK(clk),
    .D(_003_[6]),
    .Q(tap3[6])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _235_ (
    .CLK(clk),
    .D(_003_[7]),
    .Q(tap3[7])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _236_ (
    .CLK(clk),
    .D(_003_[8]),
    .Q(tap3[8])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _237_ (
    .CLK(clk),
    .D(_003_[9]),
    .Q(tap3[9])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _238_ (
    .CLK(clk),
    .D(_003_[10]),
    .Q(tap3[10])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _239_ (
    .CLK(clk),
    .D(_003_[11]),
    .Q(tap3[11])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _240_ (
    .CLK(clk),
    .D(_003_[12]),
    .Q(tap3[12])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _241_ (
    .CLK(clk),
    .D(_003_[13]),
    .Q(tap3[13])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _242_ (
    .CLK(clk),
    .D(_003_[14]),
    .Q(tap3[14])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _243_ (
    .CLK(clk),
    .D(_003_[15]),
    .Q(tap3[15])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _244_ (
    .CLK(clk),
    .D(_003_[16]),
    .Q(tap3[16])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _245_ (
    .CLK(clk),
    .D(_003_[17]),
    .Q(tap3[17])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _246_ (
    .CLK(clk),
    .D(_003_[18]),
    .Q(tap3[18])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _247_ (
    .CLK(clk),
    .D(_003_[19]),
    .Q(tap3[19])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _248_ (
    .CLK(clk),
    .D(_003_[20]),
    .Q(tap3[20])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _249_ (
    .CLK(clk),
    .D(_003_[21]),
    .Q(tap3[21])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _250_ (
    .CLK(clk),
    .D(_003_[22]),
    .Q(tap3[22])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _251_ (
    .CLK(clk),
    .D(_003_[23]),
    .Q(tap3[23])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _252_ (
    .CLK(clk),
    .D(_003_[24]),
    .Q(tap3[24])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _253_ (
    .CLK(clk),
    .D(_003_[25]),
    .Q(tap3[25])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _254_ (
    .CLK(clk),
    .D(_003_[26]),
    .Q(tap3[26])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _255_ (
    .CLK(clk),
    .D(_003_[27]),
    .Q(tap3[27])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _256_ (
    .CLK(clk),
    .D(_003_[28]),
    .Q(tap3[28])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _257_ (
    .CLK(clk),
    .D(_003_[29]),
    .Q(tap3[29])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _258_ (
    .CLK(clk),
    .D(_003_[30]),
    .Q(tap3[30])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _259_ (
    .CLK(clk),
    .D(_003_[31]),
    .Q(tap3[31])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _260_ (
    .CLK(clk),
    .D(_003_[32]),
    .Q(tap3[32])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _261_ (
    .CLK(clk),
    .D(_003_[33]),
    .Q(tap3[33])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _262_ (
    .CLK(clk),
    .D(_003_[34]),
    .Q(tap3[34])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _263_ (
    .CLK(clk),
    .D(_003_[35]),
    .Q(tap3[35])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _264_ (
    .CLK(clk),
    .D(_003_[36]),
    .Q(tap3[36])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _265_ (
    .CLK(clk),
    .D(_003_[37]),
    .Q(tap3[37])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _266_ (
    .CLK(clk),
    .D(_003_[38]),
    .Q(tap3[38])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _267_ (
    .CLK(clk),
    .D(_003_[39]),
    .Q(tap3[39])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _268_ (
    .CLK(clk),
    .D(_003_[40]),
    .Q(tap3[40])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _269_ (
    .CLK(clk),
    .D(_003_[41]),
    .Q(tap3[41])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _270_ (
    .CLK(clk),
    .D(_003_[42]),
    .Q(tap3[42])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _271_ (
    .CLK(clk),
    .D(_003_[43]),
    .Q(tap3[43])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _272_ (
    .CLK(clk),
    .D(_003_[44]),
    .Q(tap3[44])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _273_ (
    .CLK(clk),
    .D(_003_[45]),
    .Q(tap3[45])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _274_ (
    .CLK(clk),
    .D(_003_[46]),
    .Q(tap3[46])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _275_ (
    .CLK(clk),
    .D(_003_[47]),
    .Q(tap3[47])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _276_ (
    .CLK(clk),
    .D(_003_[48]),
    .Q(tap3[48])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _277_ (
    .CLK(clk),
    .D(_003_[49]),
    .Q(tap3[49])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _278_ (
    .CLK(clk),
    .D(_003_[50]),
    .Q(tap3[50])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _279_ (
    .CLK(clk),
    .D(_003_[51]),
    .Q(tap3[51])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _280_ (
    .CLK(clk),
    .D(_003_[52]),
    .Q(tap3[52])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _281_ (
    .CLK(clk),
    .D(_003_[53]),
    .Q(tap3[53])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _282_ (
    .CLK(clk),
    .D(_003_[54]),
    .Q(tap3[54])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _283_ (
    .CLK(clk),
    .D(_003_[55]),
    .Q(tap3[55])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _284_ (
    .CLK(clk),
    .D(_003_[56]),
    .Q(tap3[56])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _285_ (
    .CLK(clk),
    .D(_003_[57]),
    .Q(tap3[57])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _286_ (
    .CLK(clk),
    .D(_003_[58]),
    .Q(tap3[58])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _287_ (
    .CLK(clk),
    .D(_003_[59]),
    .Q(tap3[59])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _288_ (
    .CLK(clk),
    .D(_003_[60]),
    .Q(tap3[60])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _289_ (
    .CLK(clk),
    .D(_003_[61]),
    .Q(tap3[61])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _290_ (
    .CLK(clk),
    .D(_003_[62]),
    .Q(tap3[62])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _291_ (
    .CLK(clk),
    .D(_003_[63]),
    .Q(tap3[63])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _292_ (
    .CLK(clk),
    .D(_002_[0]),
    .Q(tap2[0])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _293_ (
    .CLK(clk),
    .D(_002_[1]),
    .Q(tap2[1])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _294_ (
    .CLK(clk),
    .D(_002_[2]),
    .Q(tap2[2])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _295_ (
    .CLK(clk),
    .D(_002_[3]),
    .Q(tap2[3])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _296_ (
    .CLK(clk),
    .D(_002_[4]),
    .Q(tap2[4])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _297_ (
    .CLK(clk),
    .D(_002_[5]),
    .Q(tap2[5])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _298_ (
    .CLK(clk),
    .D(_002_[6]),
    .Q(tap2[6])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _299_ (
    .CLK(clk),
    .D(_002_[7]),
    .Q(tap2[7])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _300_ (
    .CLK(clk),
    .D(_002_[8]),
    .Q(tap2[8])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _301_ (
    .CLK(clk),
    .D(_002_[9]),
    .Q(tap2[9])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _302_ (
    .CLK(clk),
    .D(_002_[10]),
    .Q(tap2[10])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _303_ (
    .CLK(clk),
    .D(_002_[11]),
    .Q(tap2[11])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _304_ (
    .CLK(clk),
    .D(_002_[12]),
    .Q(tap2[12])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _305_ (
    .CLK(clk),
    .D(_002_[13]),
    .Q(tap2[13])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _306_ (
    .CLK(clk),
    .D(_002_[14]),
    .Q(tap2[14])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _307_ (
    .CLK(clk),
    .D(_002_[15]),
    .Q(tap2[15])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _308_ (
    .CLK(clk),
    .D(_002_[16]),
    .Q(tap2[16])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _309_ (
    .CLK(clk),
    .D(_002_[17]),
    .Q(tap2[17])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _310_ (
    .CLK(clk),
    .D(_002_[18]),
    .Q(tap2[18])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _311_ (
    .CLK(clk),
    .D(_002_[19]),
    .Q(tap2[19])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _312_ (
    .CLK(clk),
    .D(_002_[20]),
    .Q(tap2[20])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _313_ (
    .CLK(clk),
    .D(_002_[21]),
    .Q(tap2[21])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _314_ (
    .CLK(clk),
    .D(_002_[22]),
    .Q(tap2[22])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _315_ (
    .CLK(clk),
    .D(_002_[23]),
    .Q(tap2[23])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _316_ (
    .CLK(clk),
    .D(_002_[24]),
    .Q(tap2[24])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _317_ (
    .CLK(clk),
    .D(_002_[25]),
    .Q(tap2[25])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _318_ (
    .CLK(clk),
    .D(_002_[26]),
    .Q(tap2[26])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _319_ (
    .CLK(clk),
    .D(_002_[27]),
    .Q(tap2[27])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _320_ (
    .CLK(clk),
    .D(_002_[28]),
    .Q(tap2[28])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _321_ (
    .CLK(clk),
    .D(_002_[29]),
    .Q(tap2[29])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _322_ (
    .CLK(clk),
    .D(_002_[30]),
    .Q(tap2[30])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _323_ (
    .CLK(clk),
    .D(_002_[31]),
    .Q(tap2[31])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _324_ (
    .CLK(clk),
    .D(_002_[32]),
    .Q(tap2[32])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _325_ (
    .CLK(clk),
    .D(_002_[33]),
    .Q(tap2[33])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _326_ (
    .CLK(clk),
    .D(_002_[34]),
    .Q(tap2[34])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _327_ (
    .CLK(clk),
    .D(_002_[35]),
    .Q(tap2[35])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _328_ (
    .CLK(clk),
    .D(_002_[36]),
    .Q(tap2[36])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _329_ (
    .CLK(clk),
    .D(_002_[37]),
    .Q(tap2[37])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _330_ (
    .CLK(clk),
    .D(_002_[38]),
    .Q(tap2[38])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _331_ (
    .CLK(clk),
    .D(_002_[39]),
    .Q(tap2[39])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _332_ (
    .CLK(clk),
    .D(_002_[40]),
    .Q(tap2[40])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _333_ (
    .CLK(clk),
    .D(_002_[41]),
    .Q(tap2[41])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _334_ (
    .CLK(clk),
    .D(_002_[42]),
    .Q(tap2[42])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _335_ (
    .CLK(clk),
    .D(_002_[43]),
    .Q(tap2[43])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _336_ (
    .CLK(clk),
    .D(_002_[44]),
    .Q(tap2[44])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _337_ (
    .CLK(clk),
    .D(_002_[45]),
    .Q(tap2[45])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _338_ (
    .CLK(clk),
    .D(_002_[46]),
    .Q(tap2[46])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _339_ (
    .CLK(clk),
    .D(_002_[47]),
    .Q(tap2[47])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _340_ (
    .CLK(clk),
    .D(_002_[48]),
    .Q(tap2[48])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _341_ (
    .CLK(clk),
    .D(_002_[49]),
    .Q(tap2[49])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _342_ (
    .CLK(clk),
    .D(_002_[50]),
    .Q(tap2[50])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _343_ (
    .CLK(clk),
    .D(_002_[51]),
    .Q(tap2[51])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _344_ (
    .CLK(clk),
    .D(_002_[52]),
    .Q(tap2[52])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _345_ (
    .CLK(clk),
    .D(_002_[53]),
    .Q(tap2[53])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _346_ (
    .CLK(clk),
    .D(_002_[54]),
    .Q(tap2[54])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _347_ (
    .CLK(clk),
    .D(_002_[55]),
    .Q(tap2[55])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _348_ (
    .CLK(clk),
    .D(_002_[56]),
    .Q(tap2[56])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _349_ (
    .CLK(clk),
    .D(_002_[57]),
    .Q(tap2[57])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _350_ (
    .CLK(clk),
    .D(_002_[58]),
    .Q(tap2[58])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _351_ (
    .CLK(clk),
    .D(_002_[59]),
    .Q(tap2[59])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _352_ (
    .CLK(clk),
    .D(_002_[60]),
    .Q(tap2[60])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _353_ (
    .CLK(clk),
    .D(_002_[61]),
    .Q(tap2[61])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _354_ (
    .CLK(clk),
    .D(_002_[62]),
    .Q(tap2[62])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _355_ (
    .CLK(clk),
    .D(_002_[63]),
    .Q(tap2[63])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _356_ (
    .CLK(clk),
    .D(_001_[0]),
    .Q(tap1[0])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _357_ (
    .CLK(clk),
    .D(_001_[1]),
    .Q(tap1[1])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _358_ (
    .CLK(clk),
    .D(_001_[2]),
    .Q(tap1[2])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _359_ (
    .CLK(clk),
    .D(_001_[3]),
    .Q(tap1[3])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _360_ (
    .CLK(clk),
    .D(_001_[4]),
    .Q(tap1[4])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _361_ (
    .CLK(clk),
    .D(_001_[5]),
    .Q(tap1[5])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _362_ (
    .CLK(clk),
    .D(_001_[6]),
    .Q(tap1[6])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _363_ (
    .CLK(clk),
    .D(_001_[7]),
    .Q(tap1[7])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _364_ (
    .CLK(clk),
    .D(_001_[8]),
    .Q(tap1[8])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _365_ (
    .CLK(clk),
    .D(_001_[9]),
    .Q(tap1[9])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _366_ (
    .CLK(clk),
    .D(_001_[10]),
    .Q(tap1[10])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _367_ (
    .CLK(clk),
    .D(_001_[11]),
    .Q(tap1[11])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _368_ (
    .CLK(clk),
    .D(_001_[12]),
    .Q(tap1[12])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _369_ (
    .CLK(clk),
    .D(_001_[13]),
    .Q(tap1[13])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _370_ (
    .CLK(clk),
    .D(_001_[14]),
    .Q(tap1[14])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _371_ (
    .CLK(clk),
    .D(_001_[15]),
    .Q(tap1[15])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _372_ (
    .CLK(clk),
    .D(_001_[16]),
    .Q(tap1[16])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _373_ (
    .CLK(clk),
    .D(_001_[17]),
    .Q(tap1[17])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _374_ (
    .CLK(clk),
    .D(_001_[18]),
    .Q(tap1[18])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _375_ (
    .CLK(clk),
    .D(_001_[19]),
    .Q(tap1[19])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _376_ (
    .CLK(clk),
    .D(_001_[20]),
    .Q(tap1[20])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _377_ (
    .CLK(clk),
    .D(_001_[21]),
    .Q(tap1[21])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _378_ (
    .CLK(clk),
    .D(_001_[22]),
    .Q(tap1[22])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _379_ (
    .CLK(clk),
    .D(_001_[23]),
    .Q(tap1[23])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _380_ (
    .CLK(clk),
    .D(_001_[24]),
    .Q(tap1[24])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _381_ (
    .CLK(clk),
    .D(_001_[25]),
    .Q(tap1[25])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _382_ (
    .CLK(clk),
    .D(_001_[26]),
    .Q(tap1[26])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _383_ (
    .CLK(clk),
    .D(_001_[27]),
    .Q(tap1[27])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _384_ (
    .CLK(clk),
    .D(_001_[28]),
    .Q(tap1[28])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _385_ (
    .CLK(clk),
    .D(_001_[29]),
    .Q(tap1[29])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _386_ (
    .CLK(clk),
    .D(_001_[30]),
    .Q(tap1[30])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _387_ (
    .CLK(clk),
    .D(_001_[31]),
    .Q(tap1[31])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _388_ (
    .CLK(clk),
    .D(_001_[32]),
    .Q(tap1[32])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _389_ (
    .CLK(clk),
    .D(_001_[33]),
    .Q(tap1[33])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _390_ (
    .CLK(clk),
    .D(_001_[34]),
    .Q(tap1[34])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _391_ (
    .CLK(clk),
    .D(_001_[35]),
    .Q(tap1[35])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _392_ (
    .CLK(clk),
    .D(_001_[36]),
    .Q(tap1[36])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _393_ (
    .CLK(clk),
    .D(_001_[37]),
    .Q(tap1[37])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _394_ (
    .CLK(clk),
    .D(_001_[38]),
    .Q(tap1[38])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _395_ (
    .CLK(clk),
    .D(_001_[39]),
    .Q(tap1[39])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _396_ (
    .CLK(clk),
    .D(_001_[40]),
    .Q(tap1[40])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _397_ (
    .CLK(clk),
    .D(_001_[41]),
    .Q(tap1[41])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _398_ (
    .CLK(clk),
    .D(_001_[42]),
    .Q(tap1[42])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _399_ (
    .CLK(clk),
    .D(_001_[43]),
    .Q(tap1[43])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _400_ (
    .CLK(clk),
    .D(_001_[44]),
    .Q(tap1[44])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _401_ (
    .CLK(clk),
    .D(_001_[45]),
    .Q(tap1[45])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _402_ (
    .CLK(clk),
    .D(_001_[46]),
    .Q(tap1[46])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _403_ (
    .CLK(clk),
    .D(_001_[47]),
    .Q(tap1[47])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _404_ (
    .CLK(clk),
    .D(_001_[48]),
    .Q(tap1[48])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _405_ (
    .CLK(clk),
    .D(_001_[49]),
    .Q(tap1[49])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _406_ (
    .CLK(clk),
    .D(_001_[50]),
    .Q(tap1[50])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _407_ (
    .CLK(clk),
    .D(_001_[51]),
    .Q(tap1[51])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _408_ (
    .CLK(clk),
    .D(_001_[52]),
    .Q(tap1[52])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _409_ (
    .CLK(clk),
    .D(_001_[53]),
    .Q(tap1[53])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _410_ (
    .CLK(clk),
    .D(_001_[54]),
    .Q(tap1[54])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _411_ (
    .CLK(clk),
    .D(_001_[55]),
    .Q(tap1[55])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _412_ (
    .CLK(clk),
    .D(_001_[56]),
    .Q(tap1[56])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _413_ (
    .CLK(clk),
    .D(_001_[57]),
    .Q(tap1[57])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _414_ (
    .CLK(clk),
    .D(_001_[58]),
    .Q(tap1[58])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _415_ (
    .CLK(clk),
    .D(_001_[59]),
    .Q(tap1[59])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _416_ (
    .CLK(clk),
    .D(_001_[60]),
    .Q(tap1[60])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _417_ (
    .CLK(clk),
    .D(_001_[61]),
    .Q(tap1[61])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _418_ (
    .CLK(clk),
    .D(_001_[62]),
    .Q(tap1[62])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _419_ (
    .CLK(clk),
    .D(_001_[63]),
    .Q(tap1[63])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _420_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(ctr[0])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _421_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(ctr[1])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _422_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(ctr[2])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _423_ (
    .CLK(clk),
    .D(_000_[3]),
    .Q(ctr[3])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _424_ (
    .CLK(clk),
    .D(_000_[4]),
    .Q(ctr[4])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _425_ (
    .CLK(clk),
    .D(_000_[5]),
    .Q(ctr[5])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/movavg.v:56" *)
  serialadd a1 (
    .a(din_s),
    .b(tap1[0]),
    .clk(clk),
    .s(a1_s),
    .sync(ctl1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/movavg.v:57" *)
  serialadd a2 (
    .a(tap2[0]),
    .b(tap3[0]),
    .clk(clk),
    .s(a2_s),
    .sync(ctl1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/movavg.v:61" *)
  serialadd a3 (
    .a(a1_s),
    .b(a2_s),
    .clk(clk),
    .s(a3_s),
    .sync(ctl2)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/movavg.v:44" *)
  ps stage1 (
    .a(din),
    .as(din_s),
    .clk(clk),
    .sync(ctl0)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "../rtl/movavg.v:64" *)
  sp stage9 (
    .a(dout),
    .as(a3_s),
    .clk(clk),
    .sync(ctl3)
  );
endmodule

(* src = "../rtl/movavg.v:68" *)
module ps(a, sync, clk, as);
  (* src = "../rtl/movavg.v:75" *)
  wire [63:0] _000_;
  (* src = "../rtl/movavg.v:68" *)
  input [63:0] a;
  (* src = "../rtl/movavg.v:71" *)
  output as;
  (* src = "../rtl/movavg.v:70" *)
  input clk;
  (* src = "../rtl/movavg.v:73" *)
  wire [63:0] ra;
  (* src = "../rtl/movavg.v:69" *)
  input sync;
  sky130_fd_sc_hd__mux2_1 _001_ (
    .A0(ra[2]),
    .A1(a[1]),
    .S(sync),
    .X(_000_[1])
  );
  sky130_fd_sc_hd__mux2_1 _002_ (
    .A0(ra[3]),
    .A1(a[2]),
    .S(sync),
    .X(_000_[2])
  );
  sky130_fd_sc_hd__mux2_1 _003_ (
    .A0(ra[4]),
    .A1(a[3]),
    .S(sync),
    .X(_000_[3])
  );
  sky130_fd_sc_hd__mux2_1 _004_ (
    .A0(ra[5]),
    .A1(a[4]),
    .S(sync),
    .X(_000_[4])
  );
  sky130_fd_sc_hd__mux2_1 _005_ (
    .A0(ra[6]),
    .A1(a[5]),
    .S(sync),
    .X(_000_[5])
  );
  sky130_fd_sc_hd__mux2_1 _006_ (
    .A0(ra[7]),
    .A1(a[6]),
    .S(sync),
    .X(_000_[6])
  );
  sky130_fd_sc_hd__mux2_1 _007_ (
    .A0(ra[8]),
    .A1(a[7]),
    .S(sync),
    .X(_000_[7])
  );
  sky130_fd_sc_hd__mux2_1 _008_ (
    .A0(ra[9]),
    .A1(a[8]),
    .S(sync),
    .X(_000_[8])
  );
  sky130_fd_sc_hd__mux2_1 _009_ (
    .A0(ra[10]),
    .A1(a[9]),
    .S(sync),
    .X(_000_[9])
  );
  sky130_fd_sc_hd__mux2_1 _010_ (
    .A0(ra[11]),
    .A1(a[10]),
    .S(sync),
    .X(_000_[10])
  );
  sky130_fd_sc_hd__mux2_1 _011_ (
    .A0(ra[12]),
    .A1(a[11]),
    .S(sync),
    .X(_000_[11])
  );
  sky130_fd_sc_hd__mux2_1 _012_ (
    .A0(ra[13]),
    .A1(a[12]),
    .S(sync),
    .X(_000_[12])
  );
  sky130_fd_sc_hd__mux2_1 _013_ (
    .A0(ra[14]),
    .A1(a[13]),
    .S(sync),
    .X(_000_[13])
  );
  sky130_fd_sc_hd__mux2_1 _014_ (
    .A0(ra[15]),
    .A1(a[14]),
    .S(sync),
    .X(_000_[14])
  );
  sky130_fd_sc_hd__mux2_1 _015_ (
    .A0(ra[16]),
    .A1(a[15]),
    .S(sync),
    .X(_000_[15])
  );
  sky130_fd_sc_hd__mux2_1 _016_ (
    .A0(ra[17]),
    .A1(a[16]),
    .S(sync),
    .X(_000_[16])
  );
  sky130_fd_sc_hd__mux2_1 _017_ (
    .A0(ra[18]),
    .A1(a[17]),
    .S(sync),
    .X(_000_[17])
  );
  sky130_fd_sc_hd__mux2_1 _018_ (
    .A0(ra[19]),
    .A1(a[18]),
    .S(sync),
    .X(_000_[18])
  );
  sky130_fd_sc_hd__mux2_1 _019_ (
    .A0(ra[20]),
    .A1(a[19]),
    .S(sync),
    .X(_000_[19])
  );
  sky130_fd_sc_hd__mux2_1 _020_ (
    .A0(ra[21]),
    .A1(a[20]),
    .S(sync),
    .X(_000_[20])
  );
  sky130_fd_sc_hd__mux2_1 _021_ (
    .A0(ra[22]),
    .A1(a[21]),
    .S(sync),
    .X(_000_[21])
  );
  sky130_fd_sc_hd__mux2_1 _022_ (
    .A0(ra[23]),
    .A1(a[22]),
    .S(sync),
    .X(_000_[22])
  );
  sky130_fd_sc_hd__mux2_1 _023_ (
    .A0(ra[24]),
    .A1(a[23]),
    .S(sync),
    .X(_000_[23])
  );
  sky130_fd_sc_hd__mux2_1 _024_ (
    .A0(ra[25]),
    .A1(a[24]),
    .S(sync),
    .X(_000_[24])
  );
  sky130_fd_sc_hd__mux2_1 _025_ (
    .A0(ra[26]),
    .A1(a[25]),
    .S(sync),
    .X(_000_[25])
  );
  sky130_fd_sc_hd__mux2_1 _026_ (
    .A0(ra[27]),
    .A1(a[26]),
    .S(sync),
    .X(_000_[26])
  );
  sky130_fd_sc_hd__mux2_1 _027_ (
    .A0(ra[28]),
    .A1(a[27]),
    .S(sync),
    .X(_000_[27])
  );
  sky130_fd_sc_hd__mux2_1 _028_ (
    .A0(ra[29]),
    .A1(a[28]),
    .S(sync),
    .X(_000_[28])
  );
  sky130_fd_sc_hd__mux2_1 _029_ (
    .A0(ra[30]),
    .A1(a[29]),
    .S(sync),
    .X(_000_[29])
  );
  sky130_fd_sc_hd__mux2_1 _030_ (
    .A0(ra[31]),
    .A1(a[30]),
    .S(sync),
    .X(_000_[30])
  );
  sky130_fd_sc_hd__mux2_1 _031_ (
    .A0(ra[32]),
    .A1(a[31]),
    .S(sync),
    .X(_000_[31])
  );
  sky130_fd_sc_hd__mux2_1 _032_ (
    .A0(ra[33]),
    .A1(a[32]),
    .S(sync),
    .X(_000_[32])
  );
  sky130_fd_sc_hd__mux2_1 _033_ (
    .A0(ra[34]),
    .A1(a[33]),
    .S(sync),
    .X(_000_[33])
  );
  sky130_fd_sc_hd__mux2_1 _034_ (
    .A0(ra[35]),
    .A1(a[34]),
    .S(sync),
    .X(_000_[34])
  );
  sky130_fd_sc_hd__mux2_1 _035_ (
    .A0(ra[36]),
    .A1(a[35]),
    .S(sync),
    .X(_000_[35])
  );
  sky130_fd_sc_hd__mux2_1 _036_ (
    .A0(ra[37]),
    .A1(a[36]),
    .S(sync),
    .X(_000_[36])
  );
  sky130_fd_sc_hd__mux2_1 _037_ (
    .A0(ra[38]),
    .A1(a[37]),
    .S(sync),
    .X(_000_[37])
  );
  sky130_fd_sc_hd__mux2_1 _038_ (
    .A0(ra[39]),
    .A1(a[38]),
    .S(sync),
    .X(_000_[38])
  );
  sky130_fd_sc_hd__mux2_1 _039_ (
    .A0(ra[40]),
    .A1(a[39]),
    .S(sync),
    .X(_000_[39])
  );
  sky130_fd_sc_hd__mux2_1 _040_ (
    .A0(ra[41]),
    .A1(a[40]),
    .S(sync),
    .X(_000_[40])
  );
  sky130_fd_sc_hd__mux2_1 _041_ (
    .A0(ra[42]),
    .A1(a[41]),
    .S(sync),
    .X(_000_[41])
  );
  sky130_fd_sc_hd__mux2_1 _042_ (
    .A0(ra[43]),
    .A1(a[42]),
    .S(sync),
    .X(_000_[42])
  );
  sky130_fd_sc_hd__mux2_1 _043_ (
    .A0(ra[44]),
    .A1(a[43]),
    .S(sync),
    .X(_000_[43])
  );
  sky130_fd_sc_hd__mux2_1 _044_ (
    .A0(ra[45]),
    .A1(a[44]),
    .S(sync),
    .X(_000_[44])
  );
  sky130_fd_sc_hd__mux2_1 _045_ (
    .A0(ra[46]),
    .A1(a[45]),
    .S(sync),
    .X(_000_[45])
  );
  sky130_fd_sc_hd__mux2_1 _046_ (
    .A0(ra[47]),
    .A1(a[46]),
    .S(sync),
    .X(_000_[46])
  );
  sky130_fd_sc_hd__mux2_1 _047_ (
    .A0(ra[48]),
    .A1(a[47]),
    .S(sync),
    .X(_000_[47])
  );
  sky130_fd_sc_hd__mux2_1 _048_ (
    .A0(ra[49]),
    .A1(a[48]),
    .S(sync),
    .X(_000_[48])
  );
  sky130_fd_sc_hd__mux2_1 _049_ (
    .A0(ra[50]),
    .A1(a[49]),
    .S(sync),
    .X(_000_[49])
  );
  sky130_fd_sc_hd__mux2_1 _050_ (
    .A0(ra[51]),
    .A1(a[50]),
    .S(sync),
    .X(_000_[50])
  );
  sky130_fd_sc_hd__mux2_1 _051_ (
    .A0(ra[52]),
    .A1(a[51]),
    .S(sync),
    .X(_000_[51])
  );
  sky130_fd_sc_hd__mux2_1 _052_ (
    .A0(ra[53]),
    .A1(a[52]),
    .S(sync),
    .X(_000_[52])
  );
  sky130_fd_sc_hd__mux2_1 _053_ (
    .A0(ra[54]),
    .A1(a[53]),
    .S(sync),
    .X(_000_[53])
  );
  sky130_fd_sc_hd__mux2_1 _054_ (
    .A0(ra[55]),
    .A1(a[54]),
    .S(sync),
    .X(_000_[54])
  );
  sky130_fd_sc_hd__mux2_1 _055_ (
    .A0(ra[56]),
    .A1(a[55]),
    .S(sync),
    .X(_000_[55])
  );
  sky130_fd_sc_hd__mux2_1 _056_ (
    .A0(ra[57]),
    .A1(a[56]),
    .S(sync),
    .X(_000_[56])
  );
  sky130_fd_sc_hd__mux2_1 _057_ (
    .A0(ra[58]),
    .A1(a[57]),
    .S(sync),
    .X(_000_[57])
  );
  sky130_fd_sc_hd__mux2_1 _058_ (
    .A0(ra[59]),
    .A1(a[58]),
    .S(sync),
    .X(_000_[58])
  );
  sky130_fd_sc_hd__mux2_1 _059_ (
    .A0(ra[60]),
    .A1(a[59]),
    .S(sync),
    .X(_000_[59])
  );
  sky130_fd_sc_hd__mux2_1 _060_ (
    .A0(ra[61]),
    .A1(a[60]),
    .S(sync),
    .X(_000_[60])
  );
  sky130_fd_sc_hd__mux2_1 _061_ (
    .A0(ra[62]),
    .A1(a[61]),
    .S(sync),
    .X(_000_[61])
  );
  sky130_fd_sc_hd__mux2_1 _062_ (
    .A0(ra[63]),
    .A1(a[62]),
    .S(sync),
    .X(_000_[62])
  );
  sky130_fd_sc_hd__and2_0 _063_ (
    .A(sync),
    .B(a[63]),
    .X(_000_[63])
  );
  sky130_fd_sc_hd__mux2_1 _064_ (
    .A0(ra[1]),
    .A1(a[0]),
    .S(sync),
    .X(_000_[0])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _065_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(as)
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _066_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(ra[1])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _067_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(ra[2])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _068_ (
    .CLK(clk),
    .D(_000_[3]),
    .Q(ra[3])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _069_ (
    .CLK(clk),
    .D(_000_[4]),
    .Q(ra[4])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _070_ (
    .CLK(clk),
    .D(_000_[5]),
    .Q(ra[5])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _071_ (
    .CLK(clk),
    .D(_000_[6]),
    .Q(ra[6])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _072_ (
    .CLK(clk),
    .D(_000_[7]),
    .Q(ra[7])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _073_ (
    .CLK(clk),
    .D(_000_[8]),
    .Q(ra[8])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _074_ (
    .CLK(clk),
    .D(_000_[9]),
    .Q(ra[9])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _075_ (
    .CLK(clk),
    .D(_000_[10]),
    .Q(ra[10])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _076_ (
    .CLK(clk),
    .D(_000_[11]),
    .Q(ra[11])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _077_ (
    .CLK(clk),
    .D(_000_[12]),
    .Q(ra[12])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _078_ (
    .CLK(clk),
    .D(_000_[13]),
    .Q(ra[13])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _079_ (
    .CLK(clk),
    .D(_000_[14]),
    .Q(ra[14])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _080_ (
    .CLK(clk),
    .D(_000_[15]),
    .Q(ra[15])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _081_ (
    .CLK(clk),
    .D(_000_[16]),
    .Q(ra[16])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _082_ (
    .CLK(clk),
    .D(_000_[17]),
    .Q(ra[17])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _083_ (
    .CLK(clk),
    .D(_000_[18]),
    .Q(ra[18])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _084_ (
    .CLK(clk),
    .D(_000_[19]),
    .Q(ra[19])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _085_ (
    .CLK(clk),
    .D(_000_[20]),
    .Q(ra[20])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _086_ (
    .CLK(clk),
    .D(_000_[21]),
    .Q(ra[21])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _087_ (
    .CLK(clk),
    .D(_000_[22]),
    .Q(ra[22])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _088_ (
    .CLK(clk),
    .D(_000_[23]),
    .Q(ra[23])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _089_ (
    .CLK(clk),
    .D(_000_[24]),
    .Q(ra[24])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _090_ (
    .CLK(clk),
    .D(_000_[25]),
    .Q(ra[25])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _091_ (
    .CLK(clk),
    .D(_000_[26]),
    .Q(ra[26])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _092_ (
    .CLK(clk),
    .D(_000_[27]),
    .Q(ra[27])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _093_ (
    .CLK(clk),
    .D(_000_[28]),
    .Q(ra[28])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _094_ (
    .CLK(clk),
    .D(_000_[29]),
    .Q(ra[29])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _095_ (
    .CLK(clk),
    .D(_000_[30]),
    .Q(ra[30])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _096_ (
    .CLK(clk),
    .D(_000_[31]),
    .Q(ra[31])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _097_ (
    .CLK(clk),
    .D(_000_[32]),
    .Q(ra[32])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _098_ (
    .CLK(clk),
    .D(_000_[33]),
    .Q(ra[33])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _099_ (
    .CLK(clk),
    .D(_000_[34]),
    .Q(ra[34])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _100_ (
    .CLK(clk),
    .D(_000_[35]),
    .Q(ra[35])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _101_ (
    .CLK(clk),
    .D(_000_[36]),
    .Q(ra[36])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _102_ (
    .CLK(clk),
    .D(_000_[37]),
    .Q(ra[37])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _103_ (
    .CLK(clk),
    .D(_000_[38]),
    .Q(ra[38])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _104_ (
    .CLK(clk),
    .D(_000_[39]),
    .Q(ra[39])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _105_ (
    .CLK(clk),
    .D(_000_[40]),
    .Q(ra[40])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _106_ (
    .CLK(clk),
    .D(_000_[41]),
    .Q(ra[41])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _107_ (
    .CLK(clk),
    .D(_000_[42]),
    .Q(ra[42])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _108_ (
    .CLK(clk),
    .D(_000_[43]),
    .Q(ra[43])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _109_ (
    .CLK(clk),
    .D(_000_[44]),
    .Q(ra[44])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _110_ (
    .CLK(clk),
    .D(_000_[45]),
    .Q(ra[45])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _111_ (
    .CLK(clk),
    .D(_000_[46]),
    .Q(ra[46])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _112_ (
    .CLK(clk),
    .D(_000_[47]),
    .Q(ra[47])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _113_ (
    .CLK(clk),
    .D(_000_[48]),
    .Q(ra[48])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _114_ (
    .CLK(clk),
    .D(_000_[49]),
    .Q(ra[49])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _115_ (
    .CLK(clk),
    .D(_000_[50]),
    .Q(ra[50])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _116_ (
    .CLK(clk),
    .D(_000_[51]),
    .Q(ra[51])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _117_ (
    .CLK(clk),
    .D(_000_[52]),
    .Q(ra[52])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _118_ (
    .CLK(clk),
    .D(_000_[53]),
    .Q(ra[53])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _119_ (
    .CLK(clk),
    .D(_000_[54]),
    .Q(ra[54])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _120_ (
    .CLK(clk),
    .D(_000_[55]),
    .Q(ra[55])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _121_ (
    .CLK(clk),
    .D(_000_[56]),
    .Q(ra[56])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _122_ (
    .CLK(clk),
    .D(_000_[57]),
    .Q(ra[57])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _123_ (
    .CLK(clk),
    .D(_000_[58]),
    .Q(ra[58])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _124_ (
    .CLK(clk),
    .D(_000_[59]),
    .Q(ra[59])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _125_ (
    .CLK(clk),
    .D(_000_[60]),
    .Q(ra[60])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _126_ (
    .CLK(clk),
    .D(_000_[61]),
    .Q(ra[61])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _127_ (
    .CLK(clk),
    .D(_000_[62]),
    .Q(ra[62])
  );
  (* src = "../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _128_ (
    .CLK(clk),
    .D(_000_[63]),
    .Q(ra[63])
  );
  assign ra[0] = as;
endmodule

(* src = "../rtl/movavg.v:99" *)
module serialadd(a, b, s, sync, clk);
  (* src = "../rtl/movavg.v:104" *)
  wire _0_;
  (* src = "../rtl/movavg.v:104" *)
  wire _1_;
  wire _2_;
  wire _3_;
  (* src = "../rtl/movavg.v:99" *)
  input a;
  (* src = "../rtl/movavg.v:99" *)
  input b;
  (* src = "../rtl/movavg.v:102" *)
  wire carry;
  (* src = "../rtl/movavg.v:100" *)
  input clk;
  (* src = "../rtl/movavg.v:99" *)
  output s;
  (* src = "../rtl/movavg.v:100" *)
  input sync;
  sky130_fd_sc_hd__lpflow_isobufsrc_4 _4_ (
    .A(carry),
    .SLEEP(sync),
    .X(_2_)
  );
  sky130_fd_sc_hd__xnor2_1 _5_ (
    .A(b),
    .B(a),
    .Y(_3_)
  );
  sky130_fd_sc_hd__xnor2_1 _6_ (
    .A(_2_),
    .B(_3_),
    .Y(_1_)
  );
  sky130_fd_sc_hd__maj3_2 _7_ (
    .A(b),
    .B(a),
    .C(_2_),
    .X(_0_)
  );
  (* src = "../rtl/movavg.v:104" *)
  sky130_fd_sc_hd__dfxtp_1 _8_ (
    .CLK(clk),
    .D(_0_),
    .Q(carry)
  );
  (* src = "../rtl/movavg.v:104" *)
  sky130_fd_sc_hd__dfxtp_1 _9_ (
    .CLK(clk),
    .D(_1_),
    .Q(s)
  );
endmodule

(* src = "../rtl/movavg.v:85" *)
module sp(as, sync, clk, a);
  (* src = "../rtl/movavg.v:88" *)
  output [63:0] a;
  (* src = "../rtl/movavg.v:85" *)
  input as;
  (* src = "../rtl/movavg.v:87" *)
  input clk;
  (* src = "../rtl/movavg.v:90" *)
  wire [63:0] ra;
  (* src = "../rtl/movavg.v:86" *)
  input sync;
  sky130_fd_sc_hd__and2_0 _000_ (
    .A(ra[1]),
    .B(sync),
    .X(a[1])
  );
  sky130_fd_sc_hd__and2_0 _001_ (
    .A(sync),
    .B(ra[2]),
    .X(a[2])
  );
  sky130_fd_sc_hd__and2_0 _002_ (
    .A(sync),
    .B(ra[3]),
    .X(a[3])
  );
  sky130_fd_sc_hd__and2_0 _003_ (
    .A(sync),
    .B(ra[4]),
    .X(a[4])
  );
  sky130_fd_sc_hd__and2_0 _004_ (
    .A(sync),
    .B(ra[5]),
    .X(a[5])
  );
  sky130_fd_sc_hd__and2_0 _005_ (
    .A(sync),
    .B(ra[6]),
    .X(a[6])
  );
  sky130_fd_sc_hd__and2_0 _006_ (
    .A(sync),
    .B(ra[7]),
    .X(a[7])
  );
  sky130_fd_sc_hd__and2_0 _007_ (
    .A(sync),
    .B(ra[8]),
    .X(a[8])
  );
  sky130_fd_sc_hd__and2_0 _008_ (
    .A(sync),
    .B(ra[9]),
    .X(a[9])
  );
  sky130_fd_sc_hd__and2_0 _009_ (
    .A(sync),
    .B(ra[10]),
    .X(a[10])
  );
  sky130_fd_sc_hd__and2_0 _010_ (
    .A(sync),
    .B(ra[11]),
    .X(a[11])
  );
  sky130_fd_sc_hd__and2_0 _011_ (
    .A(sync),
    .B(ra[12]),
    .X(a[12])
  );
  sky130_fd_sc_hd__and2_0 _012_ (
    .A(sync),
    .B(ra[13]),
    .X(a[13])
  );
  sky130_fd_sc_hd__and2_0 _013_ (
    .A(sync),
    .B(ra[14]),
    .X(a[14])
  );
  sky130_fd_sc_hd__and2_0 _014_ (
    .A(sync),
    .B(ra[15]),
    .X(a[15])
  );
  sky130_fd_sc_hd__and2_0 _015_ (
    .A(sync),
    .B(ra[16]),
    .X(a[16])
  );
  sky130_fd_sc_hd__and2_0 _016_ (
    .A(sync),
    .B(ra[17]),
    .X(a[17])
  );
  sky130_fd_sc_hd__and2_0 _017_ (
    .A(sync),
    .B(ra[18]),
    .X(a[18])
  );
  sky130_fd_sc_hd__and2_0 _018_ (
    .A(sync),
    .B(ra[19]),
    .X(a[19])
  );
  sky130_fd_sc_hd__and2_0 _019_ (
    .A(sync),
    .B(ra[20]),
    .X(a[20])
  );
  sky130_fd_sc_hd__and2_0 _020_ (
    .A(sync),
    .B(ra[21]),
    .X(a[21])
  );
  sky130_fd_sc_hd__and2_0 _021_ (
    .A(sync),
    .B(ra[22]),
    .X(a[22])
  );
  sky130_fd_sc_hd__and2_0 _022_ (
    .A(sync),
    .B(ra[23]),
    .X(a[23])
  );
  sky130_fd_sc_hd__and2_0 _023_ (
    .A(sync),
    .B(ra[24]),
    .X(a[24])
  );
  sky130_fd_sc_hd__and2_0 _024_ (
    .A(sync),
    .B(ra[25]),
    .X(a[25])
  );
  sky130_fd_sc_hd__and2_0 _025_ (
    .A(sync),
    .B(ra[26]),
    .X(a[26])
  );
  sky130_fd_sc_hd__and2_0 _026_ (
    .A(sync),
    .B(ra[27]),
    .X(a[27])
  );
  sky130_fd_sc_hd__and2_0 _027_ (
    .A(sync),
    .B(ra[28]),
    .X(a[28])
  );
  sky130_fd_sc_hd__and2_0 _028_ (
    .A(sync),
    .B(ra[29]),
    .X(a[29])
  );
  sky130_fd_sc_hd__and2_0 _029_ (
    .A(sync),
    .B(ra[30]),
    .X(a[30])
  );
  sky130_fd_sc_hd__and2_0 _030_ (
    .A(sync),
    .B(ra[31]),
    .X(a[31])
  );
  sky130_fd_sc_hd__and2_0 _031_ (
    .A(sync),
    .B(ra[32]),
    .X(a[32])
  );
  sky130_fd_sc_hd__and2_0 _032_ (
    .A(sync),
    .B(ra[33]),
    .X(a[33])
  );
  sky130_fd_sc_hd__and2_0 _033_ (
    .A(sync),
    .B(ra[34]),
    .X(a[34])
  );
  sky130_fd_sc_hd__and2_0 _034_ (
    .A(sync),
    .B(ra[35]),
    .X(a[35])
  );
  sky130_fd_sc_hd__and2_0 _035_ (
    .A(sync),
    .B(ra[36]),
    .X(a[36])
  );
  sky130_fd_sc_hd__and2_0 _036_ (
    .A(sync),
    .B(ra[37]),
    .X(a[37])
  );
  sky130_fd_sc_hd__and2_0 _037_ (
    .A(sync),
    .B(ra[38]),
    .X(a[38])
  );
  sky130_fd_sc_hd__and2_0 _038_ (
    .A(sync),
    .B(ra[39]),
    .X(a[39])
  );
  sky130_fd_sc_hd__and2_0 _039_ (
    .A(sync),
    .B(ra[40]),
    .X(a[40])
  );
  sky130_fd_sc_hd__and2_0 _040_ (
    .A(sync),
    .B(ra[41]),
    .X(a[41])
  );
  sky130_fd_sc_hd__and2_0 _041_ (
    .A(sync),
    .B(ra[42]),
    .X(a[42])
  );
  sky130_fd_sc_hd__and2_0 _042_ (
    .A(sync),
    .B(ra[43]),
    .X(a[43])
  );
  sky130_fd_sc_hd__and2_0 _043_ (
    .A(sync),
    .B(ra[44]),
    .X(a[44])
  );
  sky130_fd_sc_hd__and2_0 _044_ (
    .A(sync),
    .B(ra[45]),
    .X(a[45])
  );
  sky130_fd_sc_hd__and2_0 _045_ (
    .A(sync),
    .B(ra[46]),
    .X(a[46])
  );
  sky130_fd_sc_hd__and2_0 _046_ (
    .A(sync),
    .B(ra[47]),
    .X(a[47])
  );
  sky130_fd_sc_hd__and2_0 _047_ (
    .A(sync),
    .B(ra[48]),
    .X(a[48])
  );
  sky130_fd_sc_hd__and2_0 _048_ (
    .A(sync),
    .B(ra[49]),
    .X(a[49])
  );
  sky130_fd_sc_hd__and2_0 _049_ (
    .A(sync),
    .B(ra[50]),
    .X(a[50])
  );
  sky130_fd_sc_hd__and2_0 _050_ (
    .A(sync),
    .B(ra[51]),
    .X(a[51])
  );
  sky130_fd_sc_hd__and2_0 _051_ (
    .A(sync),
    .B(ra[52]),
    .X(a[52])
  );
  sky130_fd_sc_hd__and2_0 _052_ (
    .A(sync),
    .B(ra[53]),
    .X(a[53])
  );
  sky130_fd_sc_hd__and2_0 _053_ (
    .A(sync),
    .B(ra[54]),
    .X(a[54])
  );
  sky130_fd_sc_hd__and2_0 _054_ (
    .A(sync),
    .B(ra[55]),
    .X(a[55])
  );
  sky130_fd_sc_hd__and2_0 _055_ (
    .A(sync),
    .B(ra[56]),
    .X(a[56])
  );
  sky130_fd_sc_hd__and2_0 _056_ (
    .A(sync),
    .B(ra[57]),
    .X(a[57])
  );
  sky130_fd_sc_hd__and2_0 _057_ (
    .A(sync),
    .B(ra[58]),
    .X(a[58])
  );
  sky130_fd_sc_hd__and2_0 _058_ (
    .A(sync),
    .B(ra[59]),
    .X(a[59])
  );
  sky130_fd_sc_hd__and2_0 _059_ (
    .A(sync),
    .B(ra[60]),
    .X(a[60])
  );
  sky130_fd_sc_hd__and2_0 _060_ (
    .A(sync),
    .B(ra[61]),
    .X(a[61])
  );
  sky130_fd_sc_hd__and2_0 _061_ (
    .A(sync),
    .B(ra[62]),
    .X(a[62])
  );
  sky130_fd_sc_hd__and2_0 _062_ (
    .A(sync),
    .B(ra[63]),
    .X(a[63])
  );
  sky130_fd_sc_hd__and2_0 _063_ (
    .A(sync),
    .B(ra[0]),
    .X(a[0])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _064_ (
    .CLK(clk),
    .D(ra[1]),
    .Q(ra[0])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _065_ (
    .CLK(clk),
    .D(ra[2]),
    .Q(ra[1])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _066_ (
    .CLK(clk),
    .D(ra[3]),
    .Q(ra[2])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _067_ (
    .CLK(clk),
    .D(ra[4]),
    .Q(ra[3])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _068_ (
    .CLK(clk),
    .D(ra[5]),
    .Q(ra[4])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _069_ (
    .CLK(clk),
    .D(ra[6]),
    .Q(ra[5])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _070_ (
    .CLK(clk),
    .D(ra[7]),
    .Q(ra[6])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _071_ (
    .CLK(clk),
    .D(ra[8]),
    .Q(ra[7])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _072_ (
    .CLK(clk),
    .D(ra[9]),
    .Q(ra[8])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _073_ (
    .CLK(clk),
    .D(ra[10]),
    .Q(ra[9])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _074_ (
    .CLK(clk),
    .D(ra[11]),
    .Q(ra[10])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _075_ (
    .CLK(clk),
    .D(ra[12]),
    .Q(ra[11])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _076_ (
    .CLK(clk),
    .D(ra[13]),
    .Q(ra[12])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _077_ (
    .CLK(clk),
    .D(ra[14]),
    .Q(ra[13])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _078_ (
    .CLK(clk),
    .D(ra[15]),
    .Q(ra[14])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _079_ (
    .CLK(clk),
    .D(ra[16]),
    .Q(ra[15])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _080_ (
    .CLK(clk),
    .D(ra[17]),
    .Q(ra[16])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _081_ (
    .CLK(clk),
    .D(ra[18]),
    .Q(ra[17])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _082_ (
    .CLK(clk),
    .D(ra[19]),
    .Q(ra[18])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _083_ (
    .CLK(clk),
    .D(ra[20]),
    .Q(ra[19])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _084_ (
    .CLK(clk),
    .D(ra[21]),
    .Q(ra[20])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _085_ (
    .CLK(clk),
    .D(ra[22]),
    .Q(ra[21])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _086_ (
    .CLK(clk),
    .D(ra[23]),
    .Q(ra[22])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _087_ (
    .CLK(clk),
    .D(ra[24]),
    .Q(ra[23])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _088_ (
    .CLK(clk),
    .D(ra[25]),
    .Q(ra[24])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _089_ (
    .CLK(clk),
    .D(ra[26]),
    .Q(ra[25])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _090_ (
    .CLK(clk),
    .D(ra[27]),
    .Q(ra[26])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _091_ (
    .CLK(clk),
    .D(ra[28]),
    .Q(ra[27])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _092_ (
    .CLK(clk),
    .D(ra[29]),
    .Q(ra[28])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _093_ (
    .CLK(clk),
    .D(ra[30]),
    .Q(ra[29])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _094_ (
    .CLK(clk),
    .D(ra[31]),
    .Q(ra[30])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _095_ (
    .CLK(clk),
    .D(ra[32]),
    .Q(ra[31])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _096_ (
    .CLK(clk),
    .D(ra[33]),
    .Q(ra[32])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _097_ (
    .CLK(clk),
    .D(ra[34]),
    .Q(ra[33])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _098_ (
    .CLK(clk),
    .D(ra[35]),
    .Q(ra[34])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _099_ (
    .CLK(clk),
    .D(ra[36]),
    .Q(ra[35])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _100_ (
    .CLK(clk),
    .D(ra[37]),
    .Q(ra[36])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _101_ (
    .CLK(clk),
    .D(ra[38]),
    .Q(ra[37])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _102_ (
    .CLK(clk),
    .D(ra[39]),
    .Q(ra[38])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _103_ (
    .CLK(clk),
    .D(ra[40]),
    .Q(ra[39])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _104_ (
    .CLK(clk),
    .D(ra[41]),
    .Q(ra[40])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _105_ (
    .CLK(clk),
    .D(ra[42]),
    .Q(ra[41])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _106_ (
    .CLK(clk),
    .D(ra[43]),
    .Q(ra[42])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _107_ (
    .CLK(clk),
    .D(ra[44]),
    .Q(ra[43])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _108_ (
    .CLK(clk),
    .D(ra[45]),
    .Q(ra[44])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _109_ (
    .CLK(clk),
    .D(ra[46]),
    .Q(ra[45])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _110_ (
    .CLK(clk),
    .D(ra[47]),
    .Q(ra[46])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _111_ (
    .CLK(clk),
    .D(ra[48]),
    .Q(ra[47])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _112_ (
    .CLK(clk),
    .D(ra[49]),
    .Q(ra[48])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _113_ (
    .CLK(clk),
    .D(ra[50]),
    .Q(ra[49])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _114_ (
    .CLK(clk),
    .D(ra[51]),
    .Q(ra[50])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _115_ (
    .CLK(clk),
    .D(ra[52]),
    .Q(ra[51])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _116_ (
    .CLK(clk),
    .D(ra[53]),
    .Q(ra[52])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _117_ (
    .CLK(clk),
    .D(ra[54]),
    .Q(ra[53])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _118_ (
    .CLK(clk),
    .D(ra[55]),
    .Q(ra[54])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _119_ (
    .CLK(clk),
    .D(ra[56]),
    .Q(ra[55])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _120_ (
    .CLK(clk),
    .D(ra[57]),
    .Q(ra[56])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _121_ (
    .CLK(clk),
    .D(ra[58]),
    .Q(ra[57])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _122_ (
    .CLK(clk),
    .D(ra[59]),
    .Q(ra[58])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _123_ (
    .CLK(clk),
    .D(ra[60]),
    .Q(ra[59])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _124_ (
    .CLK(clk),
    .D(ra[61]),
    .Q(ra[60])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _125_ (
    .CLK(clk),
    .D(ra[62]),
    .Q(ra[61])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _126_ (
    .CLK(clk),
    .D(ra[63]),
    .Q(ra[62])
  );
  (* src = "../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _127_ (
    .CLK(clk),
    .D(as),
    .Q(ra[63])
  );
endmodule
