/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* top =  1  *)
(* src = "../rtl/movavg.v:1" *)
module movavg(clk, reset, din, dout);
  (* src = "../rtl/movavg.v:12" *)
  wire [5:0] _000_;
  (* src = "../rtl/movavg.v:12" *)
  wire [63:0] _001_;
  (* src = "../rtl/movavg.v:12" *)
  wire [63:0] _002_;
  (* src = "../rtl/movavg.v:12" *)
  wire [63:0] _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  (* src = "../rtl/movavg.v:56|../rtl/movavg.v:104" *)
  wire _029_;
  (* src = "../rtl/movavg.v:56|../rtl/movavg.v:104" *)
  wire _030_;
  (* src = "../rtl/movavg.v:57|../rtl/movavg.v:104" *)
  wire _031_;
  (* src = "../rtl/movavg.v:57|../rtl/movavg.v:104" *)
  wire _032_;
  (* src = "../rtl/movavg.v:61|../rtl/movavg.v:104" *)
  wire _033_;
  (* src = "../rtl/movavg.v:61|../rtl/movavg.v:104" *)
  wire _034_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _035_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _036_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _037_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _038_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _039_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _040_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _041_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _042_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _043_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _044_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _045_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _046_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _047_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _048_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _049_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _050_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _051_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _052_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _053_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _054_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _055_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _056_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _057_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _058_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _059_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _060_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _061_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _062_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _063_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _064_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _065_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _066_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _067_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _068_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _069_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _070_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _071_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _072_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _073_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _074_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _075_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _076_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _077_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _078_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _079_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _080_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _081_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _082_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _083_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _084_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _085_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _086_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _087_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _088_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _089_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _090_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _091_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _092_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _093_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _094_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _095_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _096_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _097_;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  wire _098_;
  (* src = "../rtl/movavg.v:56|../rtl/movavg.v:99" *)
  wire \a1.a ;
  (* src = "../rtl/movavg.v:56|../rtl/movavg.v:99" *)
  wire \a1.b ;
  (* src = "../rtl/movavg.v:56|../rtl/movavg.v:102" *)
  wire \a1.carry ;
  (* src = "../rtl/movavg.v:56|../rtl/movavg.v:100" *)
  wire \a1.clk ;
  (* src = "../rtl/movavg.v:56|../rtl/movavg.v:102" *)
  wire \a1.q ;
  (* src = "../rtl/movavg.v:56|../rtl/movavg.v:99" *)
  wire \a1.s ;
  (* src = "../rtl/movavg.v:56|../rtl/movavg.v:100" *)
  (* unused_bits = "0" *)
  wire \a1.sync ;
  (* src = "../rtl/movavg.v:55" *)
  wire a1_s;
  (* src = "../rtl/movavg.v:57|../rtl/movavg.v:99" *)
  wire \a2.a ;
  (* src = "../rtl/movavg.v:57|../rtl/movavg.v:99" *)
  wire \a2.b ;
  (* src = "../rtl/movavg.v:57|../rtl/movavg.v:102" *)
  wire \a2.carry ;
  (* src = "../rtl/movavg.v:57|../rtl/movavg.v:100" *)
  wire \a2.clk ;
  (* src = "../rtl/movavg.v:57|../rtl/movavg.v:102" *)
  wire \a2.q ;
  (* src = "../rtl/movavg.v:57|../rtl/movavg.v:99" *)
  wire \a2.s ;
  (* src = "../rtl/movavg.v:57|../rtl/movavg.v:100" *)
  (* unused_bits = "0" *)
  wire \a2.sync ;
  (* src = "../rtl/movavg.v:55" *)
  wire a2_s;
  (* src = "../rtl/movavg.v:61|../rtl/movavg.v:99" *)
  wire \a3.a ;
  (* src = "../rtl/movavg.v:61|../rtl/movavg.v:99" *)
  wire \a3.b ;
  (* src = "../rtl/movavg.v:61|../rtl/movavg.v:102" *)
  wire \a3.carry ;
  (* src = "../rtl/movavg.v:61|../rtl/movavg.v:100" *)
  wire \a3.clk ;
  (* src = "../rtl/movavg.v:61|../rtl/movavg.v:102" *)
  wire \a3.q ;
  (* src = "../rtl/movavg.v:61|../rtl/movavg.v:99" *)
  wire \a3.s ;
  (* src = "../rtl/movavg.v:60" *)
  wire a3_s;
  (* src = "../rtl/movavg.v:1" *)
  input clk;
  (* src = "../rtl/movavg.v:31" *)
  (* unused_bits = "0" *)
  wire ctl0;
  (* src = "../rtl/movavg.v:31" *)
  (* unused_bits = "0" *)
  wire ctl1;
  (* src = "../rtl/movavg.v:31" *)
  (* unused_bits = "0" *)
  wire ctl3;
  (* src = "../rtl/movavg.v:10" *)
  wire [5:0] ctr;
  (* src = "../rtl/movavg.v:3" *)
  input [63:0] din;
  (* src = "../rtl/movavg.v:43" *)
  wire din_s;
  (* src = "../rtl/movavg.v:4" *)
  output [63:0] dout;
  (* src = "../rtl/movavg.v:2" *)
  input reset;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:68" *)
  wire [63:0] \stage1.a ;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:71" *)
  wire \stage1.as ;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:70" *)
  wire \stage1.clk ;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:73" *)
  wire [63:0] \stage1.ra ;
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:69" *)
  (* unused_bits = "0" *)
  wire \stage1.sync ;
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:88" *)
  wire [63:0] \stage9.a ;
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:85" *)
  wire \stage9.as ;
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:87" *)
  wire \stage9.clk ;
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:90" *)
  wire [63:0] \stage9.ra ;
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:86" *)
  (* unused_bits = "0" *)
  wire \stage9.sync ;
  (* src = "../rtl/movavg.v:6" *)
  wire [63:0] tap1;
  (* src = "../rtl/movavg.v:6" *)
  wire [63:0] tap1_next;
  (* src = "../rtl/movavg.v:7" *)
  wire [63:0] tap2;
  (* src = "../rtl/movavg.v:7" *)
  wire [63:0] tap2_next;
  (* src = "../rtl/movavg.v:8" *)
  wire [63:0] tap3;
  (* src = "../rtl/movavg.v:8" *)
  wire [63:0] tap3_next;
  sky130_fd_sc_hd__nand2_1 _099_ (
    .A(ctr[0]),
    .B(ctr[1]),
    .Y(_004_)
  );
  sky130_fd_sc_hd__or4_1 _100_ (
    .A(ctr[2]),
    .B(ctr[3]),
    .C(ctr[4]),
    .D(ctr[5]),
    .X(_005_)
  );
  sky130_fd_sc_hd__nor2_1 _101_ (
    .A(_004_),
    .B(_005_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__and2_0 _102_ (
    .A(\stage9.ra [63]),
    .B(_006_),
    .X(dout[63])
  );
  sky130_fd_sc_hd__and2_0 _103_ (
    .A(\stage9.ra [62]),
    .B(_006_),
    .X(dout[62])
  );
  sky130_fd_sc_hd__and2_0 _104_ (
    .A(\stage9.ra [61]),
    .B(_006_),
    .X(dout[61])
  );
  sky130_fd_sc_hd__and2_0 _105_ (
    .A(\stage9.ra [60]),
    .B(_006_),
    .X(dout[60])
  );
  sky130_fd_sc_hd__and2_0 _106_ (
    .A(\stage9.ra [59]),
    .B(_006_),
    .X(dout[59])
  );
  sky130_fd_sc_hd__and2_0 _107_ (
    .A(\stage9.ra [58]),
    .B(_006_),
    .X(dout[58])
  );
  sky130_fd_sc_hd__and2_0 _108_ (
    .A(\stage9.ra [57]),
    .B(_006_),
    .X(dout[57])
  );
  sky130_fd_sc_hd__and2_0 _109_ (
    .A(\stage9.ra [56]),
    .B(_006_),
    .X(dout[56])
  );
  sky130_fd_sc_hd__and2_0 _110_ (
    .A(\stage9.ra [55]),
    .B(_006_),
    .X(dout[55])
  );
  sky130_fd_sc_hd__and2_0 _111_ (
    .A(\stage9.ra [54]),
    .B(_006_),
    .X(dout[54])
  );
  sky130_fd_sc_hd__and2_0 _112_ (
    .A(\stage9.ra [53]),
    .B(_006_),
    .X(dout[53])
  );
  sky130_fd_sc_hd__and2_0 _113_ (
    .A(\stage9.ra [52]),
    .B(_006_),
    .X(dout[52])
  );
  sky130_fd_sc_hd__and2_0 _114_ (
    .A(\stage9.ra [51]),
    .B(_006_),
    .X(dout[51])
  );
  sky130_fd_sc_hd__and2_0 _115_ (
    .A(\stage9.ra [50]),
    .B(_006_),
    .X(dout[50])
  );
  sky130_fd_sc_hd__and2_0 _116_ (
    .A(\stage9.ra [49]),
    .B(_006_),
    .X(dout[49])
  );
  sky130_fd_sc_hd__and2_0 _117_ (
    .A(\stage9.ra [48]),
    .B(_006_),
    .X(dout[48])
  );
  sky130_fd_sc_hd__and2_0 _118_ (
    .A(\stage9.ra [47]),
    .B(_006_),
    .X(dout[47])
  );
  sky130_fd_sc_hd__and2_0 _119_ (
    .A(\stage9.ra [46]),
    .B(_006_),
    .X(dout[46])
  );
  sky130_fd_sc_hd__and2_0 _120_ (
    .A(\stage9.ra [45]),
    .B(_006_),
    .X(dout[45])
  );
  sky130_fd_sc_hd__and2_0 _121_ (
    .A(\stage9.ra [44]),
    .B(_006_),
    .X(dout[44])
  );
  sky130_fd_sc_hd__and2_0 _122_ (
    .A(\stage9.ra [43]),
    .B(_006_),
    .X(dout[43])
  );
  sky130_fd_sc_hd__and2_0 _123_ (
    .A(\stage9.ra [42]),
    .B(_006_),
    .X(dout[42])
  );
  sky130_fd_sc_hd__and2_0 _124_ (
    .A(\stage9.ra [41]),
    .B(_006_),
    .X(dout[41])
  );
  sky130_fd_sc_hd__and2_0 _125_ (
    .A(\stage9.ra [40]),
    .B(_006_),
    .X(dout[40])
  );
  sky130_fd_sc_hd__and2_0 _126_ (
    .A(\stage9.ra [39]),
    .B(_006_),
    .X(dout[39])
  );
  sky130_fd_sc_hd__and2_0 _127_ (
    .A(\stage9.ra [38]),
    .B(_006_),
    .X(dout[38])
  );
  sky130_fd_sc_hd__and2_0 _128_ (
    .A(\stage9.ra [37]),
    .B(_006_),
    .X(dout[37])
  );
  sky130_fd_sc_hd__and2_0 _129_ (
    .A(\stage9.ra [36]),
    .B(_006_),
    .X(dout[36])
  );
  sky130_fd_sc_hd__and2_0 _130_ (
    .A(\stage9.ra [35]),
    .B(_006_),
    .X(dout[35])
  );
  sky130_fd_sc_hd__and2_0 _131_ (
    .A(\stage9.ra [34]),
    .B(_006_),
    .X(dout[34])
  );
  sky130_fd_sc_hd__and2_0 _132_ (
    .A(\stage9.ra [33]),
    .B(_006_),
    .X(dout[33])
  );
  sky130_fd_sc_hd__and2_0 _133_ (
    .A(\stage9.ra [32]),
    .B(_006_),
    .X(dout[32])
  );
  sky130_fd_sc_hd__and2_0 _134_ (
    .A(\stage9.ra [31]),
    .B(_006_),
    .X(dout[31])
  );
  sky130_fd_sc_hd__and2_0 _135_ (
    .A(\stage9.ra [30]),
    .B(_006_),
    .X(dout[30])
  );
  sky130_fd_sc_hd__and2_0 _136_ (
    .A(\stage9.ra [29]),
    .B(_006_),
    .X(dout[29])
  );
  sky130_fd_sc_hd__and2_0 _137_ (
    .A(\stage9.ra [28]),
    .B(_006_),
    .X(dout[28])
  );
  sky130_fd_sc_hd__and2_0 _138_ (
    .A(\stage9.ra [27]),
    .B(_006_),
    .X(dout[27])
  );
  sky130_fd_sc_hd__and2_0 _139_ (
    .A(\stage9.ra [26]),
    .B(_006_),
    .X(dout[26])
  );
  sky130_fd_sc_hd__and2_0 _140_ (
    .A(\stage9.ra [25]),
    .B(_006_),
    .X(dout[25])
  );
  sky130_fd_sc_hd__and2_0 _141_ (
    .A(\stage9.ra [24]),
    .B(_006_),
    .X(dout[24])
  );
  sky130_fd_sc_hd__and2_0 _142_ (
    .A(\stage9.ra [23]),
    .B(_006_),
    .X(dout[23])
  );
  sky130_fd_sc_hd__and2_0 _143_ (
    .A(\stage9.ra [22]),
    .B(_006_),
    .X(dout[22])
  );
  sky130_fd_sc_hd__and2_0 _144_ (
    .A(\stage9.ra [21]),
    .B(_006_),
    .X(dout[21])
  );
  sky130_fd_sc_hd__and2_0 _145_ (
    .A(\stage9.ra [20]),
    .B(_006_),
    .X(dout[20])
  );
  sky130_fd_sc_hd__and2_0 _146_ (
    .A(\stage9.ra [19]),
    .B(_006_),
    .X(dout[19])
  );
  sky130_fd_sc_hd__and2_0 _147_ (
    .A(\stage9.ra [18]),
    .B(_006_),
    .X(dout[18])
  );
  sky130_fd_sc_hd__and2_0 _148_ (
    .A(\stage9.ra [17]),
    .B(_006_),
    .X(dout[17])
  );
  sky130_fd_sc_hd__and2_0 _149_ (
    .A(\stage9.ra [16]),
    .B(_006_),
    .X(dout[16])
  );
  sky130_fd_sc_hd__and2_0 _150_ (
    .A(\stage9.ra [15]),
    .B(_006_),
    .X(dout[15])
  );
  sky130_fd_sc_hd__and2_0 _151_ (
    .A(\stage9.ra [14]),
    .B(_006_),
    .X(dout[14])
  );
  sky130_fd_sc_hd__and2_0 _152_ (
    .A(\stage9.ra [13]),
    .B(_006_),
    .X(dout[13])
  );
  sky130_fd_sc_hd__and2_0 _153_ (
    .A(\stage9.ra [12]),
    .B(_006_),
    .X(dout[12])
  );
  sky130_fd_sc_hd__and2_0 _154_ (
    .A(\stage9.ra [11]),
    .B(_006_),
    .X(dout[11])
  );
  sky130_fd_sc_hd__and2_0 _155_ (
    .A(\stage9.ra [10]),
    .B(_006_),
    .X(dout[10])
  );
  sky130_fd_sc_hd__and2_0 _156_ (
    .A(\stage9.ra [9]),
    .B(_006_),
    .X(dout[9])
  );
  sky130_fd_sc_hd__and2_0 _157_ (
    .A(\stage9.ra [8]),
    .B(_006_),
    .X(dout[8])
  );
  sky130_fd_sc_hd__and2_0 _158_ (
    .A(\stage9.ra [7]),
    .B(_006_),
    .X(dout[7])
  );
  sky130_fd_sc_hd__and2_0 _159_ (
    .A(\stage9.ra [6]),
    .B(_006_),
    .X(dout[6])
  );
  sky130_fd_sc_hd__and2_0 _160_ (
    .A(\stage9.ra [5]),
    .B(_006_),
    .X(dout[5])
  );
  sky130_fd_sc_hd__and2_0 _161_ (
    .A(\stage9.ra [4]),
    .B(_006_),
    .X(dout[4])
  );
  sky130_fd_sc_hd__and2_0 _162_ (
    .A(\stage9.ra [3]),
    .B(_006_),
    .X(dout[3])
  );
  sky130_fd_sc_hd__and2_0 _163_ (
    .A(\stage9.ra [2]),
    .B(_006_),
    .X(dout[2])
  );
  sky130_fd_sc_hd__and2_0 _164_ (
    .A(\stage9.ra [1]),
    .B(_006_),
    .X(dout[1])
  );
  sky130_fd_sc_hd__and2_0 _165_ (
    .A(\stage9.ra [0]),
    .B(_006_),
    .X(dout[0])
  );
  sky130_fd_sc_hd__nand2_1 _166_ (
    .A(\a1.q ),
    .B(\a2.q ),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nor2_1 _167_ (
    .A(\a1.q ),
    .B(\a2.q ),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nand2b_1 _168_ (
    .A_N(ctr[0]),
    .B(ctr[1]),
    .Y(_009_)
  );
  sky130_fd_sc_hd__o21ai_0 _169_ (
    .A1(_005_),
    .A2(_009_),
    .B1(\a3.carry ),
    .Y(_010_)
  );
  sky130_fd_sc_hd__a21oi_1 _170_ (
    .A1(_007_),
    .A2(_010_),
    .B1(_008_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _171_ (
    .A(_007_),
    .SLEEP(_008_),
    .X(_011_)
  );
  sky130_fd_sc_hd__xnor2_1 _172_ (
    .A(_010_),
    .B(_011_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nand2_1 _173_ (
    .A(\a2.a ),
    .B(\a2.b ),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nor2_1 _174_ (
    .A(\a2.a ),
    .B(\a2.b ),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nand2b_1 _175_ (
    .A_N(ctr[1]),
    .B(ctr[0]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__o21ai_0 _176_ (
    .A1(_005_),
    .A2(_014_),
    .B1(\a2.carry ),
    .Y(_015_)
  );
  sky130_fd_sc_hd__a21oi_1 _177_ (
    .A1(_012_),
    .A2(_015_),
    .B1(_013_),
    .Y(_031_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _178_ (
    .A(_012_),
    .SLEEP(_013_),
    .X(_016_)
  );
  sky130_fd_sc_hd__xnor2_1 _179_ (
    .A(_015_),
    .B(_016_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nand2_1 _180_ (
    .A(\a1.a ),
    .B(\a1.b ),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nor2_1 _181_ (
    .A(\a1.a ),
    .B(\a1.b ),
    .Y(_018_)
  );
  sky130_fd_sc_hd__o21ai_0 _182_ (
    .A1(_005_),
    .A2(_014_),
    .B1(\a1.carry ),
    .Y(_019_)
  );
  sky130_fd_sc_hd__a21oi_1 _183_ (
    .A1(_017_),
    .A2(_019_),
    .B1(_018_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _184_ (
    .A(_017_),
    .SLEEP(_018_),
    .X(_020_)
  );
  sky130_fd_sc_hd__xnor2_1 _185_ (
    .A(_019_),
    .B(_020_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__or3_1 _186_ (
    .A(ctr[0]),
    .B(ctr[1]),
    .C(_005_),
    .X(_021_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _187_ (
    .A(din[63]),
    .SLEEP(_021_),
    .X(_094_)
  );
  sky130_fd_sc_hd__mux2_1 _188_ (
    .A0(din[62]),
    .A1(\stage1.ra [63]),
    .S(_021_),
    .X(_093_)
  );
  sky130_fd_sc_hd__mux2_1 _189_ (
    .A0(din[61]),
    .A1(\stage1.ra [62]),
    .S(_021_),
    .X(_092_)
  );
  sky130_fd_sc_hd__mux2_1 _190_ (
    .A0(din[60]),
    .A1(\stage1.ra [61]),
    .S(_021_),
    .X(_091_)
  );
  sky130_fd_sc_hd__mux2_1 _191_ (
    .A0(din[59]),
    .A1(\stage1.ra [60]),
    .S(_021_),
    .X(_089_)
  );
  sky130_fd_sc_hd__mux2_1 _192_ (
    .A0(din[58]),
    .A1(\stage1.ra [59]),
    .S(_021_),
    .X(_088_)
  );
  sky130_fd_sc_hd__mux2_1 _193_ (
    .A0(din[57]),
    .A1(\stage1.ra [58]),
    .S(_021_),
    .X(_087_)
  );
  sky130_fd_sc_hd__mux2_1 _194_ (
    .A0(din[56]),
    .A1(\stage1.ra [57]),
    .S(_021_),
    .X(_086_)
  );
  sky130_fd_sc_hd__mux2_1 _195_ (
    .A0(din[55]),
    .A1(\stage1.ra [56]),
    .S(_021_),
    .X(_085_)
  );
  sky130_fd_sc_hd__mux2_1 _196_ (
    .A0(din[54]),
    .A1(\stage1.ra [55]),
    .S(_021_),
    .X(_084_)
  );
  sky130_fd_sc_hd__mux2_1 _197_ (
    .A0(din[53]),
    .A1(\stage1.ra [54]),
    .S(_021_),
    .X(_083_)
  );
  sky130_fd_sc_hd__mux2_1 _198_ (
    .A0(din[52]),
    .A1(\stage1.ra [53]),
    .S(_021_),
    .X(_082_)
  );
  sky130_fd_sc_hd__mux2_1 _199_ (
    .A0(din[51]),
    .A1(\stage1.ra [52]),
    .S(_021_),
    .X(_081_)
  );
  sky130_fd_sc_hd__mux2_1 _200_ (
    .A0(din[50]),
    .A1(\stage1.ra [51]),
    .S(_021_),
    .X(_080_)
  );
  sky130_fd_sc_hd__mux2_1 _201_ (
    .A0(din[49]),
    .A1(\stage1.ra [50]),
    .S(_021_),
    .X(_078_)
  );
  sky130_fd_sc_hd__mux2_1 _202_ (
    .A0(din[48]),
    .A1(\stage1.ra [49]),
    .S(_021_),
    .X(_077_)
  );
  sky130_fd_sc_hd__mux2_1 _203_ (
    .A0(din[47]),
    .A1(\stage1.ra [48]),
    .S(_021_),
    .X(_076_)
  );
  sky130_fd_sc_hd__mux2_1 _204_ (
    .A0(din[46]),
    .A1(\stage1.ra [47]),
    .S(_021_),
    .X(_075_)
  );
  sky130_fd_sc_hd__mux2_1 _205_ (
    .A0(din[45]),
    .A1(\stage1.ra [46]),
    .S(_021_),
    .X(_074_)
  );
  sky130_fd_sc_hd__mux2_1 _206_ (
    .A0(din[44]),
    .A1(\stage1.ra [45]),
    .S(_021_),
    .X(_073_)
  );
  sky130_fd_sc_hd__mux2_1 _207_ (
    .A0(din[43]),
    .A1(\stage1.ra [44]),
    .S(_021_),
    .X(_072_)
  );
  sky130_fd_sc_hd__mux2_1 _208_ (
    .A0(din[42]),
    .A1(\stage1.ra [43]),
    .S(_021_),
    .X(_071_)
  );
  sky130_fd_sc_hd__mux2_1 _209_ (
    .A0(din[41]),
    .A1(\stage1.ra [42]),
    .S(_021_),
    .X(_070_)
  );
  sky130_fd_sc_hd__mux2_1 _210_ (
    .A0(din[40]),
    .A1(\stage1.ra [41]),
    .S(_021_),
    .X(_069_)
  );
  sky130_fd_sc_hd__mux2_1 _211_ (
    .A0(din[39]),
    .A1(\stage1.ra [40]),
    .S(_021_),
    .X(_067_)
  );
  sky130_fd_sc_hd__mux2_1 _212_ (
    .A0(din[38]),
    .A1(\stage1.ra [39]),
    .S(_021_),
    .X(_066_)
  );
  sky130_fd_sc_hd__mux2_1 _213_ (
    .A0(din[37]),
    .A1(\stage1.ra [38]),
    .S(_021_),
    .X(_065_)
  );
  sky130_fd_sc_hd__mux2_1 _214_ (
    .A0(din[36]),
    .A1(\stage1.ra [37]),
    .S(_021_),
    .X(_064_)
  );
  sky130_fd_sc_hd__mux2_1 _215_ (
    .A0(din[35]),
    .A1(\stage1.ra [36]),
    .S(_021_),
    .X(_063_)
  );
  sky130_fd_sc_hd__mux2_1 _216_ (
    .A0(din[34]),
    .A1(\stage1.ra [35]),
    .S(_021_),
    .X(_062_)
  );
  sky130_fd_sc_hd__mux2_1 _217_ (
    .A0(din[33]),
    .A1(\stage1.ra [34]),
    .S(_021_),
    .X(_061_)
  );
  sky130_fd_sc_hd__mux2_1 _218_ (
    .A0(din[32]),
    .A1(\stage1.ra [33]),
    .S(_021_),
    .X(_060_)
  );
  sky130_fd_sc_hd__mux2_1 _219_ (
    .A0(din[31]),
    .A1(\stage1.ra [32]),
    .S(_021_),
    .X(_059_)
  );
  sky130_fd_sc_hd__mux2_1 _220_ (
    .A0(din[30]),
    .A1(\stage1.ra [31]),
    .S(_021_),
    .X(_058_)
  );
  sky130_fd_sc_hd__mux2_1 _221_ (
    .A0(din[29]),
    .A1(\stage1.ra [30]),
    .S(_021_),
    .X(_056_)
  );
  sky130_fd_sc_hd__mux2_1 _222_ (
    .A0(din[28]),
    .A1(\stage1.ra [29]),
    .S(_021_),
    .X(_055_)
  );
  sky130_fd_sc_hd__mux2_1 _223_ (
    .A0(din[27]),
    .A1(\stage1.ra [28]),
    .S(_021_),
    .X(_054_)
  );
  sky130_fd_sc_hd__mux2_1 _224_ (
    .A0(din[26]),
    .A1(\stage1.ra [27]),
    .S(_021_),
    .X(_053_)
  );
  sky130_fd_sc_hd__mux2_1 _225_ (
    .A0(din[25]),
    .A1(\stage1.ra [26]),
    .S(_021_),
    .X(_052_)
  );
  sky130_fd_sc_hd__mux2_1 _226_ (
    .A0(din[24]),
    .A1(\stage1.ra [25]),
    .S(_021_),
    .X(_051_)
  );
  sky130_fd_sc_hd__mux2_1 _227_ (
    .A0(din[23]),
    .A1(\stage1.ra [24]),
    .S(_021_),
    .X(_050_)
  );
  sky130_fd_sc_hd__mux2_1 _228_ (
    .A0(din[22]),
    .A1(\stage1.ra [23]),
    .S(_021_),
    .X(_049_)
  );
  sky130_fd_sc_hd__mux2_1 _229_ (
    .A0(din[21]),
    .A1(\stage1.ra [22]),
    .S(_021_),
    .X(_048_)
  );
  sky130_fd_sc_hd__mux2_1 _230_ (
    .A0(din[20]),
    .A1(\stage1.ra [21]),
    .S(_021_),
    .X(_047_)
  );
  sky130_fd_sc_hd__mux2_1 _231_ (
    .A0(din[19]),
    .A1(\stage1.ra [20]),
    .S(_021_),
    .X(_045_)
  );
  sky130_fd_sc_hd__mux2_1 _232_ (
    .A0(din[18]),
    .A1(\stage1.ra [19]),
    .S(_021_),
    .X(_044_)
  );
  sky130_fd_sc_hd__mux2_1 _233_ (
    .A0(din[17]),
    .A1(\stage1.ra [18]),
    .S(_021_),
    .X(_043_)
  );
  sky130_fd_sc_hd__mux2_1 _234_ (
    .A0(din[16]),
    .A1(\stage1.ra [17]),
    .S(_021_),
    .X(_042_)
  );
  sky130_fd_sc_hd__mux2_1 _235_ (
    .A0(din[15]),
    .A1(\stage1.ra [16]),
    .S(_021_),
    .X(_041_)
  );
  sky130_fd_sc_hd__mux2_1 _236_ (
    .A0(din[14]),
    .A1(\stage1.ra [15]),
    .S(_021_),
    .X(_040_)
  );
  sky130_fd_sc_hd__mux2_1 _237_ (
    .A0(din[13]),
    .A1(\stage1.ra [14]),
    .S(_021_),
    .X(_039_)
  );
  sky130_fd_sc_hd__mux2_1 _238_ (
    .A0(din[12]),
    .A1(\stage1.ra [13]),
    .S(_021_),
    .X(_038_)
  );
  sky130_fd_sc_hd__mux2_1 _239_ (
    .A0(din[11]),
    .A1(\stage1.ra [12]),
    .S(_021_),
    .X(_037_)
  );
  sky130_fd_sc_hd__mux2_1 _240_ (
    .A0(din[10]),
    .A1(\stage1.ra [11]),
    .S(_021_),
    .X(_036_)
  );
  sky130_fd_sc_hd__mux2_1 _241_ (
    .A0(din[9]),
    .A1(\stage1.ra [10]),
    .S(_021_),
    .X(_098_)
  );
  sky130_fd_sc_hd__mux2_1 _242_ (
    .A0(din[8]),
    .A1(\stage1.ra [9]),
    .S(_021_),
    .X(_097_)
  );
  sky130_fd_sc_hd__mux2_1 _243_ (
    .A0(din[7]),
    .A1(\stage1.ra [8]),
    .S(_021_),
    .X(_096_)
  );
  sky130_fd_sc_hd__mux2_1 _244_ (
    .A0(din[6]),
    .A1(\stage1.ra [7]),
    .S(_021_),
    .X(_095_)
  );
  sky130_fd_sc_hd__mux2_1 _245_ (
    .A0(din[5]),
    .A1(\stage1.ra [6]),
    .S(_021_),
    .X(_090_)
  );
  sky130_fd_sc_hd__mux2_1 _246_ (
    .A0(din[4]),
    .A1(\stage1.ra [5]),
    .S(_021_),
    .X(_079_)
  );
  sky130_fd_sc_hd__mux2_1 _247_ (
    .A0(din[3]),
    .A1(\stage1.ra [4]),
    .S(_021_),
    .X(_068_)
  );
  sky130_fd_sc_hd__mux2_1 _248_ (
    .A0(din[2]),
    .A1(\stage1.ra [3]),
    .S(_021_),
    .X(_057_)
  );
  sky130_fd_sc_hd__mux2_1 _249_ (
    .A0(din[1]),
    .A1(\stage1.ra [2]),
    .S(_021_),
    .X(_046_)
  );
  sky130_fd_sc_hd__mux2_1 _250_ (
    .A0(din[0]),
    .A1(\stage1.ra [1]),
    .S(_021_),
    .X(_035_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _251_ (
    .A(tap2[63]),
    .SLEEP(reset),
    .X(_002_[62])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _252_ (
    .A(\a1.b ),
    .SLEEP(reset),
    .X(_002_[63])
  );
  sky130_fd_sc_hd__nor2_1 _253_ (
    .A(reset),
    .B(ctr[0]),
    .Y(_000_[0])
  );
  sky130_fd_sc_hd__a21oi_1 _254_ (
    .A1(_009_),
    .A2(_014_),
    .B1(reset),
    .Y(_000_[1])
  );
  sky130_fd_sc_hd__and3_1 _255_ (
    .A(ctr[0]),
    .B(ctr[2]),
    .C(ctr[1]),
    .X(_022_)
  );
  sky130_fd_sc_hd__a21oi_1 _256_ (
    .A1(ctr[0]),
    .A2(ctr[1]),
    .B1(ctr[2]),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nor3_1 _257_ (
    .A(reset),
    .B(_022_),
    .C(_023_),
    .Y(_000_[2])
  );
  sky130_fd_sc_hd__and4_1 _258_ (
    .A(ctr[0]),
    .B(ctr[2]),
    .C(ctr[3]),
    .D(ctr[1]),
    .X(_024_)
  );
  sky130_fd_sc_hd__nor2_1 _259_ (
    .A(ctr[3]),
    .B(_022_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nor3_1 _260_ (
    .A(reset),
    .B(_024_),
    .C(_025_),
    .Y(_000_[3])
  );
  sky130_fd_sc_hd__a21oi_1 _261_ (
    .A1(ctr[4]),
    .A2(_024_),
    .B1(reset),
    .Y(_026_)
  );
  sky130_fd_sc_hd__o21a_1 _262_ (
    .A1(ctr[4]),
    .A2(_024_),
    .B1(_026_),
    .X(_000_[4])
  );
  sky130_fd_sc_hd__a21oi_1 _263_ (
    .A1(ctr[4]),
    .A2(_024_),
    .B1(ctr[5]),
    .Y(_027_)
  );
  sky130_fd_sc_hd__and3_1 _264_ (
    .A(ctr[4]),
    .B(ctr[5]),
    .C(_024_),
    .X(_028_)
  );
  sky130_fd_sc_hd__nor3_1 _265_ (
    .A(reset),
    .B(_027_),
    .C(_028_),
    .Y(_000_[5])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _266_ (
    .A(tap1[1]),
    .SLEEP(reset),
    .X(_001_[0])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _267_ (
    .A(tap1[2]),
    .SLEEP(reset),
    .X(_001_[1])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _268_ (
    .A(tap1[3]),
    .SLEEP(reset),
    .X(_001_[2])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _269_ (
    .A(tap1[4]),
    .SLEEP(reset),
    .X(_001_[3])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _270_ (
    .A(tap1[5]),
    .SLEEP(reset),
    .X(_001_[4])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _271_ (
    .A(tap1[6]),
    .SLEEP(reset),
    .X(_001_[5])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _272_ (
    .A(tap1[7]),
    .SLEEP(reset),
    .X(_001_[6])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _273_ (
    .A(tap1[8]),
    .SLEEP(reset),
    .X(_001_[7])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _274_ (
    .A(tap1[9]),
    .SLEEP(reset),
    .X(_001_[8])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _275_ (
    .A(tap1[10]),
    .SLEEP(reset),
    .X(_001_[9])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _276_ (
    .A(tap1[11]),
    .SLEEP(reset),
    .X(_001_[10])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _277_ (
    .A(tap1[12]),
    .SLEEP(reset),
    .X(_001_[11])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _278_ (
    .A(tap1[13]),
    .SLEEP(reset),
    .X(_001_[12])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _279_ (
    .A(tap1[14]),
    .SLEEP(reset),
    .X(_001_[13])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _280_ (
    .A(tap1[15]),
    .SLEEP(reset),
    .X(_001_[14])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _281_ (
    .A(tap1[16]),
    .SLEEP(reset),
    .X(_001_[15])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _282_ (
    .A(tap1[17]),
    .SLEEP(reset),
    .X(_001_[16])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _283_ (
    .A(tap1[18]),
    .SLEEP(reset),
    .X(_001_[17])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _284_ (
    .A(tap1[19]),
    .SLEEP(reset),
    .X(_001_[18])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _285_ (
    .A(tap1[20]),
    .SLEEP(reset),
    .X(_001_[19])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _286_ (
    .A(tap1[21]),
    .SLEEP(reset),
    .X(_001_[20])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _287_ (
    .A(tap1[22]),
    .SLEEP(reset),
    .X(_001_[21])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _288_ (
    .A(tap1[23]),
    .SLEEP(reset),
    .X(_001_[22])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _289_ (
    .A(tap1[24]),
    .SLEEP(reset),
    .X(_001_[23])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _290_ (
    .A(tap1[25]),
    .SLEEP(reset),
    .X(_001_[24])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _291_ (
    .A(tap1[26]),
    .SLEEP(reset),
    .X(_001_[25])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _292_ (
    .A(tap1[27]),
    .SLEEP(reset),
    .X(_001_[26])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _293_ (
    .A(tap1[28]),
    .SLEEP(reset),
    .X(_001_[27])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _294_ (
    .A(tap1[29]),
    .SLEEP(reset),
    .X(_001_[28])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _295_ (
    .A(tap1[30]),
    .SLEEP(reset),
    .X(_001_[29])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _296_ (
    .A(tap1[31]),
    .SLEEP(reset),
    .X(_001_[30])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _297_ (
    .A(tap1[32]),
    .SLEEP(reset),
    .X(_001_[31])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _298_ (
    .A(tap1[33]),
    .SLEEP(reset),
    .X(_001_[32])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _299_ (
    .A(tap1[34]),
    .SLEEP(reset),
    .X(_001_[33])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _300_ (
    .A(tap1[35]),
    .SLEEP(reset),
    .X(_001_[34])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _301_ (
    .A(tap1[36]),
    .SLEEP(reset),
    .X(_001_[35])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _302_ (
    .A(tap1[37]),
    .SLEEP(reset),
    .X(_001_[36])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _303_ (
    .A(tap1[38]),
    .SLEEP(reset),
    .X(_001_[37])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _304_ (
    .A(tap1[39]),
    .SLEEP(reset),
    .X(_001_[38])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _305_ (
    .A(tap1[40]),
    .SLEEP(reset),
    .X(_001_[39])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _306_ (
    .A(tap1[41]),
    .SLEEP(reset),
    .X(_001_[40])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _307_ (
    .A(tap1[42]),
    .SLEEP(reset),
    .X(_001_[41])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _308_ (
    .A(tap1[43]),
    .SLEEP(reset),
    .X(_001_[42])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _309_ (
    .A(tap1[44]),
    .SLEEP(reset),
    .X(_001_[43])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _310_ (
    .A(tap1[45]),
    .SLEEP(reset),
    .X(_001_[44])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _311_ (
    .A(tap1[46]),
    .SLEEP(reset),
    .X(_001_[45])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _312_ (
    .A(tap1[47]),
    .SLEEP(reset),
    .X(_001_[46])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _313_ (
    .A(tap1[48]),
    .SLEEP(reset),
    .X(_001_[47])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _314_ (
    .A(tap1[49]),
    .SLEEP(reset),
    .X(_001_[48])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _315_ (
    .A(tap1[50]),
    .SLEEP(reset),
    .X(_001_[49])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _316_ (
    .A(tap1[51]),
    .SLEEP(reset),
    .X(_001_[50])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _317_ (
    .A(tap1[52]),
    .SLEEP(reset),
    .X(_001_[51])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _318_ (
    .A(tap1[53]),
    .SLEEP(reset),
    .X(_001_[52])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _319_ (
    .A(tap1[54]),
    .SLEEP(reset),
    .X(_001_[53])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _320_ (
    .A(tap1[55]),
    .SLEEP(reset),
    .X(_001_[54])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _321_ (
    .A(tap1[56]),
    .SLEEP(reset),
    .X(_001_[55])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _322_ (
    .A(tap1[57]),
    .SLEEP(reset),
    .X(_001_[56])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _323_ (
    .A(tap1[58]),
    .SLEEP(reset),
    .X(_001_[57])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _324_ (
    .A(tap1[59]),
    .SLEEP(reset),
    .X(_001_[58])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _325_ (
    .A(tap1[60]),
    .SLEEP(reset),
    .X(_001_[59])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _326_ (
    .A(tap1[61]),
    .SLEEP(reset),
    .X(_001_[60])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _327_ (
    .A(tap1[62]),
    .SLEEP(reset),
    .X(_001_[61])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _328_ (
    .A(tap1[63]),
    .SLEEP(reset),
    .X(_001_[62])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _329_ (
    .A(\a1.a ),
    .SLEEP(reset),
    .X(_001_[63])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _330_ (
    .A(tap3[1]),
    .SLEEP(reset),
    .X(_003_[0])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _331_ (
    .A(tap3[2]),
    .SLEEP(reset),
    .X(_003_[1])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _332_ (
    .A(tap3[3]),
    .SLEEP(reset),
    .X(_003_[2])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _333_ (
    .A(tap3[4]),
    .SLEEP(reset),
    .X(_003_[3])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _334_ (
    .A(tap3[5]),
    .SLEEP(reset),
    .X(_003_[4])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _335_ (
    .A(tap3[6]),
    .SLEEP(reset),
    .X(_003_[5])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _336_ (
    .A(tap3[7]),
    .SLEEP(reset),
    .X(_003_[6])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _337_ (
    .A(tap3[8]),
    .SLEEP(reset),
    .X(_003_[7])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _338_ (
    .A(tap3[9]),
    .SLEEP(reset),
    .X(_003_[8])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _339_ (
    .A(tap3[10]),
    .SLEEP(reset),
    .X(_003_[9])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _340_ (
    .A(tap3[11]),
    .SLEEP(reset),
    .X(_003_[10])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _341_ (
    .A(tap3[12]),
    .SLEEP(reset),
    .X(_003_[11])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _342_ (
    .A(tap3[13]),
    .SLEEP(reset),
    .X(_003_[12])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _343_ (
    .A(tap3[14]),
    .SLEEP(reset),
    .X(_003_[13])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _344_ (
    .A(tap3[15]),
    .SLEEP(reset),
    .X(_003_[14])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _345_ (
    .A(tap3[16]),
    .SLEEP(reset),
    .X(_003_[15])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _346_ (
    .A(tap3[17]),
    .SLEEP(reset),
    .X(_003_[16])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _347_ (
    .A(tap3[18]),
    .SLEEP(reset),
    .X(_003_[17])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _348_ (
    .A(tap3[19]),
    .SLEEP(reset),
    .X(_003_[18])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _349_ (
    .A(tap3[20]),
    .SLEEP(reset),
    .X(_003_[19])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _350_ (
    .A(tap3[21]),
    .SLEEP(reset),
    .X(_003_[20])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _351_ (
    .A(tap3[22]),
    .SLEEP(reset),
    .X(_003_[21])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _352_ (
    .A(tap3[23]),
    .SLEEP(reset),
    .X(_003_[22])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _353_ (
    .A(tap3[24]),
    .SLEEP(reset),
    .X(_003_[23])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _354_ (
    .A(tap3[25]),
    .SLEEP(reset),
    .X(_003_[24])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _355_ (
    .A(tap3[26]),
    .SLEEP(reset),
    .X(_003_[25])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _356_ (
    .A(tap3[27]),
    .SLEEP(reset),
    .X(_003_[26])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _357_ (
    .A(tap3[28]),
    .SLEEP(reset),
    .X(_003_[27])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _358_ (
    .A(tap3[29]),
    .SLEEP(reset),
    .X(_003_[28])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _359_ (
    .A(tap3[30]),
    .SLEEP(reset),
    .X(_003_[29])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _360_ (
    .A(tap3[31]),
    .SLEEP(reset),
    .X(_003_[30])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _361_ (
    .A(tap3[32]),
    .SLEEP(reset),
    .X(_003_[31])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _362_ (
    .A(tap3[33]),
    .SLEEP(reset),
    .X(_003_[32])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _363_ (
    .A(tap3[34]),
    .SLEEP(reset),
    .X(_003_[33])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _364_ (
    .A(tap3[35]),
    .SLEEP(reset),
    .X(_003_[34])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _365_ (
    .A(tap3[36]),
    .SLEEP(reset),
    .X(_003_[35])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _366_ (
    .A(tap3[37]),
    .SLEEP(reset),
    .X(_003_[36])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _367_ (
    .A(tap3[38]),
    .SLEEP(reset),
    .X(_003_[37])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _368_ (
    .A(tap3[39]),
    .SLEEP(reset),
    .X(_003_[38])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _369_ (
    .A(tap3[40]),
    .SLEEP(reset),
    .X(_003_[39])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _370_ (
    .A(tap3[41]),
    .SLEEP(reset),
    .X(_003_[40])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _371_ (
    .A(tap3[42]),
    .SLEEP(reset),
    .X(_003_[41])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _372_ (
    .A(tap3[43]),
    .SLEEP(reset),
    .X(_003_[42])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _373_ (
    .A(tap3[44]),
    .SLEEP(reset),
    .X(_003_[43])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _374_ (
    .A(tap3[45]),
    .SLEEP(reset),
    .X(_003_[44])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _375_ (
    .A(tap3[46]),
    .SLEEP(reset),
    .X(_003_[45])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _376_ (
    .A(tap3[47]),
    .SLEEP(reset),
    .X(_003_[46])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _377_ (
    .A(tap3[48]),
    .SLEEP(reset),
    .X(_003_[47])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _378_ (
    .A(tap3[49]),
    .SLEEP(reset),
    .X(_003_[48])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _379_ (
    .A(tap3[50]),
    .SLEEP(reset),
    .X(_003_[49])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _380_ (
    .A(tap3[51]),
    .SLEEP(reset),
    .X(_003_[50])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _381_ (
    .A(tap3[52]),
    .SLEEP(reset),
    .X(_003_[51])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _382_ (
    .A(tap3[53]),
    .SLEEP(reset),
    .X(_003_[52])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _383_ (
    .A(tap3[54]),
    .SLEEP(reset),
    .X(_003_[53])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _384_ (
    .A(tap3[55]),
    .SLEEP(reset),
    .X(_003_[54])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _385_ (
    .A(tap3[56]),
    .SLEEP(reset),
    .X(_003_[55])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _386_ (
    .A(tap3[57]),
    .SLEEP(reset),
    .X(_003_[56])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _387_ (
    .A(tap3[58]),
    .SLEEP(reset),
    .X(_003_[57])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _388_ (
    .A(tap3[59]),
    .SLEEP(reset),
    .X(_003_[58])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _389_ (
    .A(tap3[60]),
    .SLEEP(reset),
    .X(_003_[59])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _390_ (
    .A(tap3[61]),
    .SLEEP(reset),
    .X(_003_[60])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _391_ (
    .A(tap3[62]),
    .SLEEP(reset),
    .X(_003_[61])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _392_ (
    .A(tap3[63]),
    .SLEEP(reset),
    .X(_003_[62])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _393_ (
    .A(\a2.a ),
    .SLEEP(reset),
    .X(_003_[63])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _394_ (
    .A(tap2[1]),
    .SLEEP(reset),
    .X(_002_[0])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _395_ (
    .A(tap2[2]),
    .SLEEP(reset),
    .X(_002_[1])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _396_ (
    .A(tap2[3]),
    .SLEEP(reset),
    .X(_002_[2])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _397_ (
    .A(tap2[4]),
    .SLEEP(reset),
    .X(_002_[3])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _398_ (
    .A(tap2[5]),
    .SLEEP(reset),
    .X(_002_[4])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _399_ (
    .A(tap2[6]),
    .SLEEP(reset),
    .X(_002_[5])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _400_ (
    .A(tap2[7]),
    .SLEEP(reset),
    .X(_002_[6])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _401_ (
    .A(tap2[8]),
    .SLEEP(reset),
    .X(_002_[7])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _402_ (
    .A(tap2[9]),
    .SLEEP(reset),
    .X(_002_[8])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _403_ (
    .A(tap2[10]),
    .SLEEP(reset),
    .X(_002_[9])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _404_ (
    .A(tap2[11]),
    .SLEEP(reset),
    .X(_002_[10])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _405_ (
    .A(tap2[12]),
    .SLEEP(reset),
    .X(_002_[11])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _406_ (
    .A(tap2[13]),
    .SLEEP(reset),
    .X(_002_[12])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _407_ (
    .A(tap2[14]),
    .SLEEP(reset),
    .X(_002_[13])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _408_ (
    .A(tap2[15]),
    .SLEEP(reset),
    .X(_002_[14])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _409_ (
    .A(tap2[16]),
    .SLEEP(reset),
    .X(_002_[15])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _410_ (
    .A(tap2[17]),
    .SLEEP(reset),
    .X(_002_[16])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _411_ (
    .A(tap2[18]),
    .SLEEP(reset),
    .X(_002_[17])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _412_ (
    .A(tap2[19]),
    .SLEEP(reset),
    .X(_002_[18])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _413_ (
    .A(tap2[20]),
    .SLEEP(reset),
    .X(_002_[19])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _414_ (
    .A(tap2[21]),
    .SLEEP(reset),
    .X(_002_[20])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _415_ (
    .A(tap2[22]),
    .SLEEP(reset),
    .X(_002_[21])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _416_ (
    .A(tap2[23]),
    .SLEEP(reset),
    .X(_002_[22])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _417_ (
    .A(tap2[24]),
    .SLEEP(reset),
    .X(_002_[23])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _418_ (
    .A(tap2[25]),
    .SLEEP(reset),
    .X(_002_[24])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _419_ (
    .A(tap2[26]),
    .SLEEP(reset),
    .X(_002_[25])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _420_ (
    .A(tap2[27]),
    .SLEEP(reset),
    .X(_002_[26])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _421_ (
    .A(tap2[28]),
    .SLEEP(reset),
    .X(_002_[27])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _422_ (
    .A(tap2[29]),
    .SLEEP(reset),
    .X(_002_[28])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _423_ (
    .A(tap2[30]),
    .SLEEP(reset),
    .X(_002_[29])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _424_ (
    .A(tap2[31]),
    .SLEEP(reset),
    .X(_002_[30])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _425_ (
    .A(tap2[32]),
    .SLEEP(reset),
    .X(_002_[31])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _426_ (
    .A(tap2[33]),
    .SLEEP(reset),
    .X(_002_[32])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _427_ (
    .A(tap2[34]),
    .SLEEP(reset),
    .X(_002_[33])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _428_ (
    .A(tap2[35]),
    .SLEEP(reset),
    .X(_002_[34])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _429_ (
    .A(tap2[36]),
    .SLEEP(reset),
    .X(_002_[35])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _430_ (
    .A(tap2[37]),
    .SLEEP(reset),
    .X(_002_[36])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _431_ (
    .A(tap2[38]),
    .SLEEP(reset),
    .X(_002_[37])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _432_ (
    .A(tap2[39]),
    .SLEEP(reset),
    .X(_002_[38])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _433_ (
    .A(tap2[40]),
    .SLEEP(reset),
    .X(_002_[39])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _434_ (
    .A(tap2[41]),
    .SLEEP(reset),
    .X(_002_[40])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _435_ (
    .A(tap2[42]),
    .SLEEP(reset),
    .X(_002_[41])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _436_ (
    .A(tap2[43]),
    .SLEEP(reset),
    .X(_002_[42])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _437_ (
    .A(tap2[44]),
    .SLEEP(reset),
    .X(_002_[43])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _438_ (
    .A(tap2[45]),
    .SLEEP(reset),
    .X(_002_[44])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _439_ (
    .A(tap2[46]),
    .SLEEP(reset),
    .X(_002_[45])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _440_ (
    .A(tap2[47]),
    .SLEEP(reset),
    .X(_002_[46])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _441_ (
    .A(tap2[48]),
    .SLEEP(reset),
    .X(_002_[47])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _442_ (
    .A(tap2[49]),
    .SLEEP(reset),
    .X(_002_[48])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _443_ (
    .A(tap2[50]),
    .SLEEP(reset),
    .X(_002_[49])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _444_ (
    .A(tap2[51]),
    .SLEEP(reset),
    .X(_002_[50])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _445_ (
    .A(tap2[52]),
    .SLEEP(reset),
    .X(_002_[51])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _446_ (
    .A(tap2[53]),
    .SLEEP(reset),
    .X(_002_[52])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _447_ (
    .A(tap2[54]),
    .SLEEP(reset),
    .X(_002_[53])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _448_ (
    .A(tap2[55]),
    .SLEEP(reset),
    .X(_002_[54])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _449_ (
    .A(tap2[56]),
    .SLEEP(reset),
    .X(_002_[55])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _450_ (
    .A(tap2[57]),
    .SLEEP(reset),
    .X(_002_[56])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _451_ (
    .A(tap2[58]),
    .SLEEP(reset),
    .X(_002_[57])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _452_ (
    .A(tap2[59]),
    .SLEEP(reset),
    .X(_002_[58])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _453_ (
    .A(tap2[60]),
    .SLEEP(reset),
    .X(_002_[59])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _454_ (
    .A(tap2[61]),
    .SLEEP(reset),
    .X(_002_[60])
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _455_ (
    .A(tap2[62]),
    .SLEEP(reset),
    .X(_002_[61])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _456_ (
    .CLK(clk),
    .D(_003_[0]),
    .Q(\a2.b )
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _457_ (
    .CLK(clk),
    .D(_003_[1]),
    .Q(tap3[1])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _458_ (
    .CLK(clk),
    .D(_003_[2]),
    .Q(tap3[2])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _459_ (
    .CLK(clk),
    .D(_003_[3]),
    .Q(tap3[3])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _460_ (
    .CLK(clk),
    .D(_003_[4]),
    .Q(tap3[4])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _461_ (
    .CLK(clk),
    .D(_003_[5]),
    .Q(tap3[5])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _462_ (
    .CLK(clk),
    .D(_003_[6]),
    .Q(tap3[6])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _463_ (
    .CLK(clk),
    .D(_003_[7]),
    .Q(tap3[7])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _464_ (
    .CLK(clk),
    .D(_003_[8]),
    .Q(tap3[8])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _465_ (
    .CLK(clk),
    .D(_003_[9]),
    .Q(tap3[9])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _466_ (
    .CLK(clk),
    .D(_003_[10]),
    .Q(tap3[10])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _467_ (
    .CLK(clk),
    .D(_003_[11]),
    .Q(tap3[11])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _468_ (
    .CLK(clk),
    .D(_003_[12]),
    .Q(tap3[12])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _469_ (
    .CLK(clk),
    .D(_003_[13]),
    .Q(tap3[13])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _470_ (
    .CLK(clk),
    .D(_003_[14]),
    .Q(tap3[14])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _471_ (
    .CLK(clk),
    .D(_003_[15]),
    .Q(tap3[15])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _472_ (
    .CLK(clk),
    .D(_003_[16]),
    .Q(tap3[16])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _473_ (
    .CLK(clk),
    .D(_003_[17]),
    .Q(tap3[17])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _474_ (
    .CLK(clk),
    .D(_003_[18]),
    .Q(tap3[18])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _475_ (
    .CLK(clk),
    .D(_003_[19]),
    .Q(tap3[19])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _476_ (
    .CLK(clk),
    .D(_003_[20]),
    .Q(tap3[20])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _477_ (
    .CLK(clk),
    .D(_003_[21]),
    .Q(tap3[21])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _478_ (
    .CLK(clk),
    .D(_003_[22]),
    .Q(tap3[22])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _479_ (
    .CLK(clk),
    .D(_003_[23]),
    .Q(tap3[23])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _480_ (
    .CLK(clk),
    .D(_003_[24]),
    .Q(tap3[24])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _481_ (
    .CLK(clk),
    .D(_003_[25]),
    .Q(tap3[25])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _482_ (
    .CLK(clk),
    .D(_003_[26]),
    .Q(tap3[26])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _483_ (
    .CLK(clk),
    .D(_003_[27]),
    .Q(tap3[27])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _484_ (
    .CLK(clk),
    .D(_003_[28]),
    .Q(tap3[28])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _485_ (
    .CLK(clk),
    .D(_003_[29]),
    .Q(tap3[29])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _486_ (
    .CLK(clk),
    .D(_003_[30]),
    .Q(tap3[30])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _487_ (
    .CLK(clk),
    .D(_003_[31]),
    .Q(tap3[31])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _488_ (
    .CLK(clk),
    .D(_003_[32]),
    .Q(tap3[32])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _489_ (
    .CLK(clk),
    .D(_003_[33]),
    .Q(tap3[33])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _490_ (
    .CLK(clk),
    .D(_003_[34]),
    .Q(tap3[34])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _491_ (
    .CLK(clk),
    .D(_003_[35]),
    .Q(tap3[35])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _492_ (
    .CLK(clk),
    .D(_003_[36]),
    .Q(tap3[36])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _493_ (
    .CLK(clk),
    .D(_003_[37]),
    .Q(tap3[37])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _494_ (
    .CLK(clk),
    .D(_003_[38]),
    .Q(tap3[38])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _495_ (
    .CLK(clk),
    .D(_003_[39]),
    .Q(tap3[39])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _496_ (
    .CLK(clk),
    .D(_003_[40]),
    .Q(tap3[40])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _497_ (
    .CLK(clk),
    .D(_003_[41]),
    .Q(tap3[41])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _498_ (
    .CLK(clk),
    .D(_003_[42]),
    .Q(tap3[42])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _499_ (
    .CLK(clk),
    .D(_003_[43]),
    .Q(tap3[43])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _500_ (
    .CLK(clk),
    .D(_003_[44]),
    .Q(tap3[44])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _501_ (
    .CLK(clk),
    .D(_003_[45]),
    .Q(tap3[45])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _502_ (
    .CLK(clk),
    .D(_003_[46]),
    .Q(tap3[46])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _503_ (
    .CLK(clk),
    .D(_003_[47]),
    .Q(tap3[47])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _504_ (
    .CLK(clk),
    .D(_003_[48]),
    .Q(tap3[48])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _505_ (
    .CLK(clk),
    .D(_003_[49]),
    .Q(tap3[49])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _506_ (
    .CLK(clk),
    .D(_003_[50]),
    .Q(tap3[50])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _507_ (
    .CLK(clk),
    .D(_003_[51]),
    .Q(tap3[51])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _508_ (
    .CLK(clk),
    .D(_003_[52]),
    .Q(tap3[52])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _509_ (
    .CLK(clk),
    .D(_003_[53]),
    .Q(tap3[53])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _510_ (
    .CLK(clk),
    .D(_003_[54]),
    .Q(tap3[54])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _511_ (
    .CLK(clk),
    .D(_003_[55]),
    .Q(tap3[55])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _512_ (
    .CLK(clk),
    .D(_003_[56]),
    .Q(tap3[56])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _513_ (
    .CLK(clk),
    .D(_003_[57]),
    .Q(tap3[57])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _514_ (
    .CLK(clk),
    .D(_003_[58]),
    .Q(tap3[58])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _515_ (
    .CLK(clk),
    .D(_003_[59]),
    .Q(tap3[59])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _516_ (
    .CLK(clk),
    .D(_003_[60]),
    .Q(tap3[60])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _517_ (
    .CLK(clk),
    .D(_003_[61]),
    .Q(tap3[61])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _518_ (
    .CLK(clk),
    .D(_003_[62]),
    .Q(tap3[62])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _519_ (
    .CLK(clk),
    .D(_003_[63]),
    .Q(tap3[63])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _520_ (
    .CLK(clk),
    .D(_002_[0]),
    .Q(\a2.a )
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _521_ (
    .CLK(clk),
    .D(_002_[1]),
    .Q(tap2[1])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _522_ (
    .CLK(clk),
    .D(_002_[2]),
    .Q(tap2[2])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _523_ (
    .CLK(clk),
    .D(_002_[3]),
    .Q(tap2[3])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _524_ (
    .CLK(clk),
    .D(_002_[4]),
    .Q(tap2[4])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _525_ (
    .CLK(clk),
    .D(_002_[5]),
    .Q(tap2[5])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _526_ (
    .CLK(clk),
    .D(_002_[6]),
    .Q(tap2[6])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _527_ (
    .CLK(clk),
    .D(_002_[7]),
    .Q(tap2[7])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _528_ (
    .CLK(clk),
    .D(_002_[8]),
    .Q(tap2[8])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _529_ (
    .CLK(clk),
    .D(_002_[9]),
    .Q(tap2[9])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _530_ (
    .CLK(clk),
    .D(_002_[10]),
    .Q(tap2[10])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _531_ (
    .CLK(clk),
    .D(_002_[11]),
    .Q(tap2[11])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _532_ (
    .CLK(clk),
    .D(_002_[12]),
    .Q(tap2[12])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _533_ (
    .CLK(clk),
    .D(_002_[13]),
    .Q(tap2[13])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _534_ (
    .CLK(clk),
    .D(_002_[14]),
    .Q(tap2[14])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _535_ (
    .CLK(clk),
    .D(_002_[15]),
    .Q(tap2[15])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _536_ (
    .CLK(clk),
    .D(_002_[16]),
    .Q(tap2[16])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _537_ (
    .CLK(clk),
    .D(_002_[17]),
    .Q(tap2[17])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _538_ (
    .CLK(clk),
    .D(_002_[18]),
    .Q(tap2[18])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _539_ (
    .CLK(clk),
    .D(_002_[19]),
    .Q(tap2[19])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _540_ (
    .CLK(clk),
    .D(_002_[20]),
    .Q(tap2[20])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _541_ (
    .CLK(clk),
    .D(_002_[21]),
    .Q(tap2[21])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _542_ (
    .CLK(clk),
    .D(_002_[22]),
    .Q(tap2[22])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _543_ (
    .CLK(clk),
    .D(_002_[23]),
    .Q(tap2[23])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _544_ (
    .CLK(clk),
    .D(_002_[24]),
    .Q(tap2[24])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _545_ (
    .CLK(clk),
    .D(_002_[25]),
    .Q(tap2[25])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _546_ (
    .CLK(clk),
    .D(_002_[26]),
    .Q(tap2[26])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _547_ (
    .CLK(clk),
    .D(_002_[27]),
    .Q(tap2[27])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _548_ (
    .CLK(clk),
    .D(_002_[28]),
    .Q(tap2[28])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _549_ (
    .CLK(clk),
    .D(_002_[29]),
    .Q(tap2[29])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _550_ (
    .CLK(clk),
    .D(_002_[30]),
    .Q(tap2[30])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _551_ (
    .CLK(clk),
    .D(_002_[31]),
    .Q(tap2[31])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _552_ (
    .CLK(clk),
    .D(_002_[32]),
    .Q(tap2[32])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _553_ (
    .CLK(clk),
    .D(_002_[33]),
    .Q(tap2[33])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _554_ (
    .CLK(clk),
    .D(_002_[34]),
    .Q(tap2[34])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _555_ (
    .CLK(clk),
    .D(_002_[35]),
    .Q(tap2[35])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _556_ (
    .CLK(clk),
    .D(_002_[36]),
    .Q(tap2[36])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _557_ (
    .CLK(clk),
    .D(_002_[37]),
    .Q(tap2[37])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _558_ (
    .CLK(clk),
    .D(_002_[38]),
    .Q(tap2[38])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _559_ (
    .CLK(clk),
    .D(_002_[39]),
    .Q(tap2[39])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _560_ (
    .CLK(clk),
    .D(_002_[40]),
    .Q(tap2[40])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _561_ (
    .CLK(clk),
    .D(_002_[41]),
    .Q(tap2[41])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _562_ (
    .CLK(clk),
    .D(_002_[42]),
    .Q(tap2[42])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _563_ (
    .CLK(clk),
    .D(_002_[43]),
    .Q(tap2[43])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _564_ (
    .CLK(clk),
    .D(_002_[44]),
    .Q(tap2[44])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _565_ (
    .CLK(clk),
    .D(_002_[45]),
    .Q(tap2[45])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _566_ (
    .CLK(clk),
    .D(_002_[46]),
    .Q(tap2[46])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _567_ (
    .CLK(clk),
    .D(_002_[47]),
    .Q(tap2[47])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _568_ (
    .CLK(clk),
    .D(_002_[48]),
    .Q(tap2[48])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _569_ (
    .CLK(clk),
    .D(_002_[49]),
    .Q(tap2[49])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _570_ (
    .CLK(clk),
    .D(_002_[50]),
    .Q(tap2[50])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _571_ (
    .CLK(clk),
    .D(_002_[51]),
    .Q(tap2[51])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _572_ (
    .CLK(clk),
    .D(_002_[52]),
    .Q(tap2[52])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _573_ (
    .CLK(clk),
    .D(_002_[53]),
    .Q(tap2[53])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _574_ (
    .CLK(clk),
    .D(_002_[54]),
    .Q(tap2[54])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _575_ (
    .CLK(clk),
    .D(_002_[55]),
    .Q(tap2[55])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _576_ (
    .CLK(clk),
    .D(_002_[56]),
    .Q(tap2[56])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _577_ (
    .CLK(clk),
    .D(_002_[57]),
    .Q(tap2[57])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _578_ (
    .CLK(clk),
    .D(_002_[58]),
    .Q(tap2[58])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _579_ (
    .CLK(clk),
    .D(_002_[59]),
    .Q(tap2[59])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _580_ (
    .CLK(clk),
    .D(_002_[60]),
    .Q(tap2[60])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _581_ (
    .CLK(clk),
    .D(_002_[61]),
    .Q(tap2[61])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _582_ (
    .CLK(clk),
    .D(_002_[62]),
    .Q(tap2[62])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _583_ (
    .CLK(clk),
    .D(_002_[63]),
    .Q(tap2[63])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _584_ (
    .CLK(clk),
    .D(_001_[0]),
    .Q(\a1.b )
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _585_ (
    .CLK(clk),
    .D(_001_[1]),
    .Q(tap1[1])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _586_ (
    .CLK(clk),
    .D(_001_[2]),
    .Q(tap1[2])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _587_ (
    .CLK(clk),
    .D(_001_[3]),
    .Q(tap1[3])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _588_ (
    .CLK(clk),
    .D(_001_[4]),
    .Q(tap1[4])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _589_ (
    .CLK(clk),
    .D(_001_[5]),
    .Q(tap1[5])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _590_ (
    .CLK(clk),
    .D(_001_[6]),
    .Q(tap1[6])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _591_ (
    .CLK(clk),
    .D(_001_[7]),
    .Q(tap1[7])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _592_ (
    .CLK(clk),
    .D(_001_[8]),
    .Q(tap1[8])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _593_ (
    .CLK(clk),
    .D(_001_[9]),
    .Q(tap1[9])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _594_ (
    .CLK(clk),
    .D(_001_[10]),
    .Q(tap1[10])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _595_ (
    .CLK(clk),
    .D(_001_[11]),
    .Q(tap1[11])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _596_ (
    .CLK(clk),
    .D(_001_[12]),
    .Q(tap1[12])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _597_ (
    .CLK(clk),
    .D(_001_[13]),
    .Q(tap1[13])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _598_ (
    .CLK(clk),
    .D(_001_[14]),
    .Q(tap1[14])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _599_ (
    .CLK(clk),
    .D(_001_[15]),
    .Q(tap1[15])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _600_ (
    .CLK(clk),
    .D(_001_[16]),
    .Q(tap1[16])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _601_ (
    .CLK(clk),
    .D(_001_[17]),
    .Q(tap1[17])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _602_ (
    .CLK(clk),
    .D(_001_[18]),
    .Q(tap1[18])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _603_ (
    .CLK(clk),
    .D(_001_[19]),
    .Q(tap1[19])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _604_ (
    .CLK(clk),
    .D(_001_[20]),
    .Q(tap1[20])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _605_ (
    .CLK(clk),
    .D(_001_[21]),
    .Q(tap1[21])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _606_ (
    .CLK(clk),
    .D(_001_[22]),
    .Q(tap1[22])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _607_ (
    .CLK(clk),
    .D(_001_[23]),
    .Q(tap1[23])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _608_ (
    .CLK(clk),
    .D(_001_[24]),
    .Q(tap1[24])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _609_ (
    .CLK(clk),
    .D(_001_[25]),
    .Q(tap1[25])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _610_ (
    .CLK(clk),
    .D(_001_[26]),
    .Q(tap1[26])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _611_ (
    .CLK(clk),
    .D(_001_[27]),
    .Q(tap1[27])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _612_ (
    .CLK(clk),
    .D(_001_[28]),
    .Q(tap1[28])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _613_ (
    .CLK(clk),
    .D(_001_[29]),
    .Q(tap1[29])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _614_ (
    .CLK(clk),
    .D(_001_[30]),
    .Q(tap1[30])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _615_ (
    .CLK(clk),
    .D(_001_[31]),
    .Q(tap1[31])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _616_ (
    .CLK(clk),
    .D(_001_[32]),
    .Q(tap1[32])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _617_ (
    .CLK(clk),
    .D(_001_[33]),
    .Q(tap1[33])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _618_ (
    .CLK(clk),
    .D(_001_[34]),
    .Q(tap1[34])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _619_ (
    .CLK(clk),
    .D(_001_[35]),
    .Q(tap1[35])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _620_ (
    .CLK(clk),
    .D(_001_[36]),
    .Q(tap1[36])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _621_ (
    .CLK(clk),
    .D(_001_[37]),
    .Q(tap1[37])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _622_ (
    .CLK(clk),
    .D(_001_[38]),
    .Q(tap1[38])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _623_ (
    .CLK(clk),
    .D(_001_[39]),
    .Q(tap1[39])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _624_ (
    .CLK(clk),
    .D(_001_[40]),
    .Q(tap1[40])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _625_ (
    .CLK(clk),
    .D(_001_[41]),
    .Q(tap1[41])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _626_ (
    .CLK(clk),
    .D(_001_[42]),
    .Q(tap1[42])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _627_ (
    .CLK(clk),
    .D(_001_[43]),
    .Q(tap1[43])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _628_ (
    .CLK(clk),
    .D(_001_[44]),
    .Q(tap1[44])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _629_ (
    .CLK(clk),
    .D(_001_[45]),
    .Q(tap1[45])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _630_ (
    .CLK(clk),
    .D(_001_[46]),
    .Q(tap1[46])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _631_ (
    .CLK(clk),
    .D(_001_[47]),
    .Q(tap1[47])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _632_ (
    .CLK(clk),
    .D(_001_[48]),
    .Q(tap1[48])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _633_ (
    .CLK(clk),
    .D(_001_[49]),
    .Q(tap1[49])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _634_ (
    .CLK(clk),
    .D(_001_[50]),
    .Q(tap1[50])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _635_ (
    .CLK(clk),
    .D(_001_[51]),
    .Q(tap1[51])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _636_ (
    .CLK(clk),
    .D(_001_[52]),
    .Q(tap1[52])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _637_ (
    .CLK(clk),
    .D(_001_[53]),
    .Q(tap1[53])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _638_ (
    .CLK(clk),
    .D(_001_[54]),
    .Q(tap1[54])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _639_ (
    .CLK(clk),
    .D(_001_[55]),
    .Q(tap1[55])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _640_ (
    .CLK(clk),
    .D(_001_[56]),
    .Q(tap1[56])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _641_ (
    .CLK(clk),
    .D(_001_[57]),
    .Q(tap1[57])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _642_ (
    .CLK(clk),
    .D(_001_[58]),
    .Q(tap1[58])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _643_ (
    .CLK(clk),
    .D(_001_[59]),
    .Q(tap1[59])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _644_ (
    .CLK(clk),
    .D(_001_[60]),
    .Q(tap1[60])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _645_ (
    .CLK(clk),
    .D(_001_[61]),
    .Q(tap1[61])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _646_ (
    .CLK(clk),
    .D(_001_[62]),
    .Q(tap1[62])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _647_ (
    .CLK(clk),
    .D(_001_[63]),
    .Q(tap1[63])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _648_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(ctr[0])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _649_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(ctr[1])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _650_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(ctr[2])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _651_ (
    .CLK(clk),
    .D(_000_[3]),
    .Q(ctr[3])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _652_ (
    .CLK(clk),
    .D(_000_[4]),
    .Q(ctr[4])
  );
  (* src = "../rtl/movavg.v:12" *)
  sky130_fd_sc_hd__dfxtp_1 _653_ (
    .CLK(clk),
    .D(_000_[5]),
    .Q(ctr[5])
  );
  (* src = "../rtl/movavg.v:56|../rtl/movavg.v:104" *)
  sky130_fd_sc_hd__dfxtp_1 _654_ (
    .CLK(clk),
    .D(_029_),
    .Q(\a1.carry )
  );
  (* src = "../rtl/movavg.v:56|../rtl/movavg.v:104" *)
  sky130_fd_sc_hd__dfxtp_1 _655_ (
    .CLK(clk),
    .D(_030_),
    .Q(\a1.q )
  );
  (* src = "../rtl/movavg.v:57|../rtl/movavg.v:104" *)
  sky130_fd_sc_hd__dfxtp_1 _656_ (
    .CLK(clk),
    .D(_031_),
    .Q(\a2.carry )
  );
  (* src = "../rtl/movavg.v:57|../rtl/movavg.v:104" *)
  sky130_fd_sc_hd__dfxtp_1 _657_ (
    .CLK(clk),
    .D(_032_),
    .Q(\a2.q )
  );
  (* src = "../rtl/movavg.v:61|../rtl/movavg.v:104" *)
  sky130_fd_sc_hd__dfxtp_1 _658_ (
    .CLK(clk),
    .D(_033_),
    .Q(\a3.carry )
  );
  (* src = "../rtl/movavg.v:61|../rtl/movavg.v:104" *)
  sky130_fd_sc_hd__dfxtp_1 _659_ (
    .CLK(clk),
    .D(_034_),
    .Q(\a3.q )
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _660_ (
    .CLK(clk),
    .D(_035_),
    .Q(\a1.a )
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _661_ (
    .CLK(clk),
    .D(_046_),
    .Q(\stage1.ra [1])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _662_ (
    .CLK(clk),
    .D(_057_),
    .Q(\stage1.ra [2])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _663_ (
    .CLK(clk),
    .D(_068_),
    .Q(\stage1.ra [3])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _664_ (
    .CLK(clk),
    .D(_079_),
    .Q(\stage1.ra [4])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _665_ (
    .CLK(clk),
    .D(_090_),
    .Q(\stage1.ra [5])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _666_ (
    .CLK(clk),
    .D(_095_),
    .Q(\stage1.ra [6])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _667_ (
    .CLK(clk),
    .D(_096_),
    .Q(\stage1.ra [7])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _668_ (
    .CLK(clk),
    .D(_097_),
    .Q(\stage1.ra [8])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _669_ (
    .CLK(clk),
    .D(_098_),
    .Q(\stage1.ra [9])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _670_ (
    .CLK(clk),
    .D(_036_),
    .Q(\stage1.ra [10])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _671_ (
    .CLK(clk),
    .D(_037_),
    .Q(\stage1.ra [11])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _672_ (
    .CLK(clk),
    .D(_038_),
    .Q(\stage1.ra [12])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _673_ (
    .CLK(clk),
    .D(_039_),
    .Q(\stage1.ra [13])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _674_ (
    .CLK(clk),
    .D(_040_),
    .Q(\stage1.ra [14])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _675_ (
    .CLK(clk),
    .D(_041_),
    .Q(\stage1.ra [15])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _676_ (
    .CLK(clk),
    .D(_042_),
    .Q(\stage1.ra [16])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _677_ (
    .CLK(clk),
    .D(_043_),
    .Q(\stage1.ra [17])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _678_ (
    .CLK(clk),
    .D(_044_),
    .Q(\stage1.ra [18])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _679_ (
    .CLK(clk),
    .D(_045_),
    .Q(\stage1.ra [19])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _680_ (
    .CLK(clk),
    .D(_047_),
    .Q(\stage1.ra [20])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _681_ (
    .CLK(clk),
    .D(_048_),
    .Q(\stage1.ra [21])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _682_ (
    .CLK(clk),
    .D(_049_),
    .Q(\stage1.ra [22])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _683_ (
    .CLK(clk),
    .D(_050_),
    .Q(\stage1.ra [23])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _684_ (
    .CLK(clk),
    .D(_051_),
    .Q(\stage1.ra [24])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _685_ (
    .CLK(clk),
    .D(_052_),
    .Q(\stage1.ra [25])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _686_ (
    .CLK(clk),
    .D(_053_),
    .Q(\stage1.ra [26])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _687_ (
    .CLK(clk),
    .D(_054_),
    .Q(\stage1.ra [27])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _688_ (
    .CLK(clk),
    .D(_055_),
    .Q(\stage1.ra [28])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _689_ (
    .CLK(clk),
    .D(_056_),
    .Q(\stage1.ra [29])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _690_ (
    .CLK(clk),
    .D(_058_),
    .Q(\stage1.ra [30])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _691_ (
    .CLK(clk),
    .D(_059_),
    .Q(\stage1.ra [31])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _692_ (
    .CLK(clk),
    .D(_060_),
    .Q(\stage1.ra [32])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _693_ (
    .CLK(clk),
    .D(_061_),
    .Q(\stage1.ra [33])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _694_ (
    .CLK(clk),
    .D(_062_),
    .Q(\stage1.ra [34])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _695_ (
    .CLK(clk),
    .D(_063_),
    .Q(\stage1.ra [35])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _696_ (
    .CLK(clk),
    .D(_064_),
    .Q(\stage1.ra [36])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _697_ (
    .CLK(clk),
    .D(_065_),
    .Q(\stage1.ra [37])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _698_ (
    .CLK(clk),
    .D(_066_),
    .Q(\stage1.ra [38])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _699_ (
    .CLK(clk),
    .D(_067_),
    .Q(\stage1.ra [39])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _700_ (
    .CLK(clk),
    .D(_069_),
    .Q(\stage1.ra [40])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _701_ (
    .CLK(clk),
    .D(_070_),
    .Q(\stage1.ra [41])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _702_ (
    .CLK(clk),
    .D(_071_),
    .Q(\stage1.ra [42])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _703_ (
    .CLK(clk),
    .D(_072_),
    .Q(\stage1.ra [43])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _704_ (
    .CLK(clk),
    .D(_073_),
    .Q(\stage1.ra [44])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _705_ (
    .CLK(clk),
    .D(_074_),
    .Q(\stage1.ra [45])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _706_ (
    .CLK(clk),
    .D(_075_),
    .Q(\stage1.ra [46])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _707_ (
    .CLK(clk),
    .D(_076_),
    .Q(\stage1.ra [47])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _708_ (
    .CLK(clk),
    .D(_077_),
    .Q(\stage1.ra [48])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _709_ (
    .CLK(clk),
    .D(_078_),
    .Q(\stage1.ra [49])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _710_ (
    .CLK(clk),
    .D(_080_),
    .Q(\stage1.ra [50])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _711_ (
    .CLK(clk),
    .D(_081_),
    .Q(\stage1.ra [51])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _712_ (
    .CLK(clk),
    .D(_082_),
    .Q(\stage1.ra [52])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _713_ (
    .CLK(clk),
    .D(_083_),
    .Q(\stage1.ra [53])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _714_ (
    .CLK(clk),
    .D(_084_),
    .Q(\stage1.ra [54])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _715_ (
    .CLK(clk),
    .D(_085_),
    .Q(\stage1.ra [55])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _716_ (
    .CLK(clk),
    .D(_086_),
    .Q(\stage1.ra [56])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _717_ (
    .CLK(clk),
    .D(_087_),
    .Q(\stage1.ra [57])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _718_ (
    .CLK(clk),
    .D(_088_),
    .Q(\stage1.ra [58])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _719_ (
    .CLK(clk),
    .D(_089_),
    .Q(\stage1.ra [59])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _720_ (
    .CLK(clk),
    .D(_091_),
    .Q(\stage1.ra [60])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _721_ (
    .CLK(clk),
    .D(_092_),
    .Q(\stage1.ra [61])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _722_ (
    .CLK(clk),
    .D(_093_),
    .Q(\stage1.ra [62])
  );
  (* src = "../rtl/movavg.v:44|../rtl/movavg.v:75" *)
  sky130_fd_sc_hd__dfxtp_1 _723_ (
    .CLK(clk),
    .D(_094_),
    .Q(\stage1.ra [63])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _724_ (
    .CLK(clk),
    .D(\stage9.ra [1]),
    .Q(\stage9.ra [0])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _725_ (
    .CLK(clk),
    .D(\stage9.ra [2]),
    .Q(\stage9.ra [1])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _726_ (
    .CLK(clk),
    .D(\stage9.ra [3]),
    .Q(\stage9.ra [2])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _727_ (
    .CLK(clk),
    .D(\stage9.ra [4]),
    .Q(\stage9.ra [3])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _728_ (
    .CLK(clk),
    .D(\stage9.ra [5]),
    .Q(\stage9.ra [4])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _729_ (
    .CLK(clk),
    .D(\stage9.ra [6]),
    .Q(\stage9.ra [5])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _730_ (
    .CLK(clk),
    .D(\stage9.ra [7]),
    .Q(\stage9.ra [6])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _731_ (
    .CLK(clk),
    .D(\stage9.ra [8]),
    .Q(\stage9.ra [7])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _732_ (
    .CLK(clk),
    .D(\stage9.ra [9]),
    .Q(\stage9.ra [8])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _733_ (
    .CLK(clk),
    .D(\stage9.ra [10]),
    .Q(\stage9.ra [9])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _734_ (
    .CLK(clk),
    .D(\stage9.ra [11]),
    .Q(\stage9.ra [10])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _735_ (
    .CLK(clk),
    .D(\stage9.ra [12]),
    .Q(\stage9.ra [11])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _736_ (
    .CLK(clk),
    .D(\stage9.ra [13]),
    .Q(\stage9.ra [12])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _737_ (
    .CLK(clk),
    .D(\stage9.ra [14]),
    .Q(\stage9.ra [13])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _738_ (
    .CLK(clk),
    .D(\stage9.ra [15]),
    .Q(\stage9.ra [14])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _739_ (
    .CLK(clk),
    .D(\stage9.ra [16]),
    .Q(\stage9.ra [15])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _740_ (
    .CLK(clk),
    .D(\stage9.ra [17]),
    .Q(\stage9.ra [16])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _741_ (
    .CLK(clk),
    .D(\stage9.ra [18]),
    .Q(\stage9.ra [17])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _742_ (
    .CLK(clk),
    .D(\stage9.ra [19]),
    .Q(\stage9.ra [18])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _743_ (
    .CLK(clk),
    .D(\stage9.ra [20]),
    .Q(\stage9.ra [19])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _744_ (
    .CLK(clk),
    .D(\stage9.ra [21]),
    .Q(\stage9.ra [20])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _745_ (
    .CLK(clk),
    .D(\stage9.ra [22]),
    .Q(\stage9.ra [21])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _746_ (
    .CLK(clk),
    .D(\stage9.ra [23]),
    .Q(\stage9.ra [22])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _747_ (
    .CLK(clk),
    .D(\stage9.ra [24]),
    .Q(\stage9.ra [23])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _748_ (
    .CLK(clk),
    .D(\stage9.ra [25]),
    .Q(\stage9.ra [24])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _749_ (
    .CLK(clk),
    .D(\stage9.ra [26]),
    .Q(\stage9.ra [25])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _750_ (
    .CLK(clk),
    .D(\stage9.ra [27]),
    .Q(\stage9.ra [26])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _751_ (
    .CLK(clk),
    .D(\stage9.ra [28]),
    .Q(\stage9.ra [27])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _752_ (
    .CLK(clk),
    .D(\stage9.ra [29]),
    .Q(\stage9.ra [28])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _753_ (
    .CLK(clk),
    .D(\stage9.ra [30]),
    .Q(\stage9.ra [29])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _754_ (
    .CLK(clk),
    .D(\stage9.ra [31]),
    .Q(\stage9.ra [30])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _755_ (
    .CLK(clk),
    .D(\stage9.ra [32]),
    .Q(\stage9.ra [31])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _756_ (
    .CLK(clk),
    .D(\stage9.ra [33]),
    .Q(\stage9.ra [32])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _757_ (
    .CLK(clk),
    .D(\stage9.ra [34]),
    .Q(\stage9.ra [33])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _758_ (
    .CLK(clk),
    .D(\stage9.ra [35]),
    .Q(\stage9.ra [34])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _759_ (
    .CLK(clk),
    .D(\stage9.ra [36]),
    .Q(\stage9.ra [35])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _760_ (
    .CLK(clk),
    .D(\stage9.ra [37]),
    .Q(\stage9.ra [36])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _761_ (
    .CLK(clk),
    .D(\stage9.ra [38]),
    .Q(\stage9.ra [37])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _762_ (
    .CLK(clk),
    .D(\stage9.ra [39]),
    .Q(\stage9.ra [38])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _763_ (
    .CLK(clk),
    .D(\stage9.ra [40]),
    .Q(\stage9.ra [39])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _764_ (
    .CLK(clk),
    .D(\stage9.ra [41]),
    .Q(\stage9.ra [40])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _765_ (
    .CLK(clk),
    .D(\stage9.ra [42]),
    .Q(\stage9.ra [41])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _766_ (
    .CLK(clk),
    .D(\stage9.ra [43]),
    .Q(\stage9.ra [42])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _767_ (
    .CLK(clk),
    .D(\stage9.ra [44]),
    .Q(\stage9.ra [43])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _768_ (
    .CLK(clk),
    .D(\stage9.ra [45]),
    .Q(\stage9.ra [44])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _769_ (
    .CLK(clk),
    .D(\stage9.ra [46]),
    .Q(\stage9.ra [45])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _770_ (
    .CLK(clk),
    .D(\stage9.ra [47]),
    .Q(\stage9.ra [46])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _771_ (
    .CLK(clk),
    .D(\stage9.ra [48]),
    .Q(\stage9.ra [47])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _772_ (
    .CLK(clk),
    .D(\stage9.ra [49]),
    .Q(\stage9.ra [48])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _773_ (
    .CLK(clk),
    .D(\stage9.ra [50]),
    .Q(\stage9.ra [49])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _774_ (
    .CLK(clk),
    .D(\stage9.ra [51]),
    .Q(\stage9.ra [50])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _775_ (
    .CLK(clk),
    .D(\stage9.ra [52]),
    .Q(\stage9.ra [51])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _776_ (
    .CLK(clk),
    .D(\stage9.ra [53]),
    .Q(\stage9.ra [52])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _777_ (
    .CLK(clk),
    .D(\stage9.ra [54]),
    .Q(\stage9.ra [53])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _778_ (
    .CLK(clk),
    .D(\stage9.ra [55]),
    .Q(\stage9.ra [54])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _779_ (
    .CLK(clk),
    .D(\stage9.ra [56]),
    .Q(\stage9.ra [55])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _780_ (
    .CLK(clk),
    .D(\stage9.ra [57]),
    .Q(\stage9.ra [56])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _781_ (
    .CLK(clk),
    .D(\stage9.ra [58]),
    .Q(\stage9.ra [57])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _782_ (
    .CLK(clk),
    .D(\stage9.ra [59]),
    .Q(\stage9.ra [58])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _783_ (
    .CLK(clk),
    .D(\stage9.ra [60]),
    .Q(\stage9.ra [59])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _784_ (
    .CLK(clk),
    .D(\stage9.ra [61]),
    .Q(\stage9.ra [60])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _785_ (
    .CLK(clk),
    .D(\stage9.ra [62]),
    .Q(\stage9.ra [61])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _786_ (
    .CLK(clk),
    .D(\stage9.ra [63]),
    .Q(\stage9.ra [62])
  );
  (* src = "../rtl/movavg.v:64|../rtl/movavg.v:92" *)
  sky130_fd_sc_hd__dfxtp_1 _787_ (
    .CLK(clk),
    .D(\a3.q ),
    .Q(\stage9.ra [63])
  );
  assign \stage9.sync  = ctl3;
  assign \stage9.clk  = clk;
  assign \stage9.as  = \a3.q ;
  assign \stage9.a  = dout;
  assign \a3.s  = \a3.q ;
  assign \a3.clk  = clk;
  assign \a3.b  = \a2.q ;
  assign \a3.a  = \a1.q ;
  assign \a2.sync  = \a1.sync ;
  assign \a2.s  = \a2.q ;
  assign \a2.clk  = clk;
  assign \a1.s  = \a1.q ;
  assign \a1.clk  = clk;
  assign \stage1.sync  = ctl0;
  assign \stage1.ra [0] = \a1.a ;
  assign \stage1.clk  = clk;
  assign \stage1.as  = \a1.a ;
  assign \stage1.a  = din;
  assign a1_s = \a1.q ;
  assign a2_s = \a2.q ;
  assign a3_s = \a3.q ;
  assign ctl1 = \a1.sync ;
  assign din_s = \a1.a ;
  assign tap1[0] = \a1.b ;
  assign tap1_next = { \a1.a , tap1[63:1] };
  assign tap2[0] = \a2.a ;
  assign tap2_next = { \a1.b , tap2[63:1] };
  assign tap3[0] = \a2.b ;
  assign tap3_next = { \a2.a , tap3[63:1] };
endmodule
